configuration.md
Detail documentation on how to proceed so as to connect the backend and frontend together.
#107
=> Documentation for connecting backend with frontend

configuration.md
Fixes #132 .
Just fixes a spelling error. Changes "Remeber" at line 87 to "Remember".
=> Fixed a typo in Configuration.md

.github/workflows/issue.yml
Details here: https://github.com/Renato66/auto-label
Set default label to: "PR-Unapproved"
=> Added 'Auto Label' GitHub Action

package.json
Updates the package.json to make the module more recognisable and relevant.
This PR fixes #101 .
=> Updates package.json to reflect server details

index.js
merging this will allow the url to be hit more number of times in 15 min which will ease the speed of debugging the app.
Fixes #148
=> [Enhancement] Increased the number of requested made in 15min

index.js
=> fix: Usage of helmet in default configuration blocks graphql playground to open

.github/workflows/issue.yml, CONTRIBUTING.md, package.json, resolvers/Query.js, schema/event/event.graphql, schema/newsfeed/newsfeed.graphql, schema/organization/organization.graphql, schema/query.graphql, schema/user/user.graphql
Following query are modified with `orderBy` parameters to filter the retrieve data requested by client (Mobile user) in specific order (Issue #161).
To return organized list data in a certain specific order as requested by the client (Mobile User).
User Query Example: 
https://user-images.githubusercontent.com/35868598/111555872-4ca76f00-87af-11eb-9a28-3fda841c5638.mov
```
Following filter created for Users Query:
1. id_ASC
2. id_DESC
3. firstName_ASC
4. firstName_DESC
5. lastName_ASC
6. lastName_DESC
7. email_ASC
8. email_DESC
```
Organization Query Example: 
https://user-images.githubusercontent.com/35868598/111556016-9c863600-87af-11eb-96e9-4d3458c95b0d.mov
```
Following filter created for Organizations Query:
1. id_ASC
2. id_DESC
3. name_ASC
4. name_DESC
5. description_ASC
6. …
```
=> [Enhancement] Adding orderBy filter in query

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/pull_request_template.md
=> bug, feature and pull request template added

package-lock.json, package.json
=> chore: Remove unused packages

index.js, schema/query.graphql
Refactoring of query to introduce filtering capability(#161)
As the change was introduced in parameter of already built queries so no need to exclusively add tests.
Currently no exclusive documentation exists explaining the api
**Summary**
This will help to optimize the frontend
It gives filtering capability to queries
=> Adding orderBy filtering capability to queries

CONTRIBUTING.md, PR-guidelines.md, issue-guidelines.md
=> Initial draft for contribution guidelines and templates

resolvers/event_mutations/createEvent.js, resolvers/event_mutations/registerForEvent.js, resolvers/event_project_mutations/createProject.js, resolvers/membership_request_mutations/reject_membership_request.js, resolvers/project_task_mutations/createTask.js
Closes #183 
1. Uses the latest form of auth checking in the codebase for a few mutations. 
2. Adds auth checking to an unauthenticated mutation.
Relevant tests are already present. 
**Summary**
Adds necessary auth checking and the latest way of auth checking for a few resolvers.
=> fix: Few files are following the old way of auth checking

models/DirectChatMessage.js, models/GroupChatMessage.js
Fix #173  
Modification
No test case added but tested locally for this new change.
No
**Summary**
This is the modification of the model `GroupChatMessage` and `DirectChatMessage`.
The motivation behind this is to increase the consistency and quality of a code.
No
=> modified the createdAt field inside the models

resolvers/Mutation.js
Bugfix. Issue #188 
Not required here
No not required
**Summary**
fix develop branch
No
=> [BugFix] Develop branch fix

package.json
This package Chalk will help in giving an informative color to console logs.
This Package can be used in index.js file to show catchy console messages which will help developer to know exactly what is happening
=> New Package Chalk

index.js
Color to messages in console
I have given red color to console log if there is error in connecting to database and a catchy golden color if connection to database is successful .Hope you will like it :)
=> More Informative Console Logs in Index.js.

package-lock.json, package.json
Updated jest to the latest version so it now uses node-notifier 8.0.0
No
No
**Summary**
Jest has a vulnerability which I am working on.
No
=> Updated jest to latest version

helper_functions/uploadImage.js, index.js, package-lock.json, package.json, resolvers/Mutation.js, schema/schema.graphql
Fixes #219 
I explained the whole bug in issue #219 and i have resolved it using graphql-upload package @Sagar2366 sir.
Basically the current apollo version which is being used in the project does not support image upload .So we have got two choices either to downgrade node js to version 12 or use graphql-upload. So according to me it would be difficult for everyone to downgrade node js , that's why use of graphql-upload is the best choice.
=> Bug during file upload resolved.

package-lock.json, package.json, resolvers/push_notifications/notifications.js
This PR adds the feature for push notifications using 3rd party and solves issue #207
No
No
**Summary**
I feel push notifications are necessary for an application to attract more users and keep them engaged.
No
We used a 3rd party FCM plugin to send push notifications.
=> 3rd party notification system issue #207

resolvers/Mutation.js, schema/schema.graphql, tests/user_update.spec.js
Bugfix for issue #170 
Yes this is the test code for PR #176 
No documentation update needed.
**Summary**
Test code will make sure that future changes are not destroying the past developments. 
No
Test code will work only after PR #176 will be live in the link
=> Test code for updateProfileMutation

CONTRIBUTING.md
Updated the CONTRIBUTING.md to include the alpha and develop branches
N/A
Yes
No
=> Updated branching strategy in CONTRIBUTING.md

package-lock.json, package.json
Security patch by updating netmask library
N/A
N/A
**Summary**
No
=> Bump up netmask due to security issue

package-lock.json, package.json
bugfix
N/A
N/A
**Summary**
Upgraded jest which internally uses node-notifier
No
=> bugFix: #254 Bumped up node-notifier

models/User.js, package-lock.json, package.json, resolvers/Query.js, resolvers/user_query/users_pagination.js, resolvers/user_query/users_utils.js, schema/query.graphql, schema/schema.graphql, schema/user/user.graphql, schema/utils.graphql
Closes #247 
No
Not necessary
**Summary**
Pagination for members of organization
No
=> Pagination for members of organization

models/User.js, resolvers/Mutation.js, resolvers/language_mutation/updateLanguage.js, schema/mutation.graphql, schema/user/user.graphql
Closes #280 
No
Not required
**Summary**
User Model and Schema will be updated so that user language can be stored
No
UPDATE LANGUAGE MUTATION
https://user-images.githubusercontent.com/35868598/119628827-14658200-be2b-11eb-9d33-247ad89ccda7.mov
=> Model and Schema update for appLanguage

schema/newsfeed/newsfeed.graphql
Bugfix 
Closes #295 
Fixes #
Not required here
Not needed
**Summary**
Schema is organised for pagination
No
=> Schema Update to avoid master failure

package-lock.json, package.json
Solves issue #288 by bumping ws parent dependencies.
#288
Fixes #
No
**Summary**
No
=> buFix: #288 bump ws parent dependencies

package-lock.json, package.json
Package update
Fixes #288 
Fixes #
No
**Summary**
=> bugFix: #288 develop ws bump

package-lock.json, package.json
I have added yarn package since it is faster than npm which will help project to run faster
=> Added yarn package since it is faster than npm

models/Comment.js, models/DirectChat.js, models/DirectChatMessage.js, models/Event.js, models/EventProject.js, models/Group.js, models/GroupChat.js, models/GroupChatMessage.js, models/ImageHash.js, models/MembershipRequest.js, models/Message.js, models/Organization.js, models/Post.js, models/Task.js, models/User.js
feature #310 
Fixes #310 
Not needed here
Not needed here
**Summary**
Access parameter will help in maintaining record in DB
No
=> Schema modification

directives/roleDirective.js, index.js, schema/mutation.graphql, schema/schema.graphql
Added a role-based authorization directive that checks if the requesting user is a user/admin/super-admin
Fixes #298 
No
https://user-images.githubusercontent.com/51146347/125109108-8c001f80-e100-11eb-8c76-746cde4fe068.mp4
Not required
No
N/A
Yes
=> added role based authorization directive

models/Comment.js, models/Plugins.js, models/PluginsField.js, resolvers/Mutation.js, resolvers/plugin_mutations/createPlugin.js, schema/mutation.graphql, schema/plugin/plugin.graphql, schema/plugin/pluginField.graphql, schema/schema.graphql, schema/user/user.graphql, schema/utils.graphql
Feature #327 
Fixes #327
No
Not needed
**Summary**
Require for supporting Reetik Work
No
=> Create Plugin Mutation and Model Updates

models/Plugins.js, resolvers/Query.js, resolvers/functions/superAdminCheck.js, resolvers/plugin_query/admin-plugin-query.js, resolvers/plugin_query/super-admin-plugin-query.js, schema/mutation.graphql, schema/plugin/plugin.graphql, schema/query.graphql, schema/utils.graphql
feature
Fixes #339
No
Not needed
**Summary**
No
Yes
=> [GSoC] Plugin-query-creation

index.js, models/Chat.js, models/Message.js, package-lock.json, package.json, resolvers/Mutation.js, resolvers/Subscription.js, resolvers/message_chat_mutation/createMessageChat.js, schema/chats/message.graphql, schema/mutation.graphql, schema/query.graphql, schema/schema.graphql
feature 
Fixes #335 
Not needed
https://user-images.githubusercontent.com/35868598/129625103-913ecc34-1f1a-4b4a-822f-b37431621f6e.mov
No
**Summary**
No
Chat Subscription for user communication
Yes
=> [GSoC] Chat feature

index.js
bugfix
Fixes #342
No
Not needed
**Summary**
Some of the API's require three-layer access
No
Yes
=> [GSoC] Depth set to 3

resolvers/Query.js, resolvers/user_query/myLanguage.js, resolvers/user_query/userLanguage.js, schema/query.graphql
feature
Fixes https://github.com/PalisadoesFoundation/talawa/issues/807
No
Not needed
**Summary**
No
No
=> [GSoC] Language query added

models/Language.js, resolvers/Mutation.js, resolvers/Query.js, resolvers/language_maintainer_mutation/addLanguageTranslation.js, resolvers/language_maintainer_query/getlanguage.js, schema/Language/lang.graphql, schema/mutation.graphql, schema/query.graphql, schema/schema.graphql
feature
Fixes https://github.com/PalisadoesFoundation/talawa/issues/808https://github.com/PalisadoesFoundation/talawa/issues/808
No
Not needed
**Summary**
No
This is used to add language packets by talawa-admin
Yes
=> [GSoC] Language packets

.github/workflows/authorized-changes-detection.yml, .github/workflows/pull-request-target.yml, .github/workflows/pull-request.yml, CODEOWNERS
=> Fix first interaction,added CODEOWNERS,add unauthorized PR checks

tests/language.spec.js
Adds tests for updateLanguage Mutation.
Fixes #365 
No.
Yes.
=> Add test for updateLanguage mutation

tests/users_connection.spec.js
testing
Fixes #368 
Yes
**Summary**
- Fixes issue #368 
No.
Yes
=> Test: Added User Connection Query Test

resolvers/direct_chat_mutations/sendMessageToDirectChat.js, resolvers/group_chat_mutations/sendMessageToGroupChat.js
bugfix
Fixes #431 
Yes
**Summary**
- Solves issue #431 
- Fixes `sendMessageToGroupChat` and `sendMessageToDirectChat` Mutation
No
Yes
=> Fixed Send Message Mutation

backend-api-documentation.md, resolvers/Query.js, resolvers/direct_chat_query/directChatsByUserID.js, schema/query.graphql
**[Urgent approval needed for frotend app work}**
This is a graphql used to find directChats related with a specific user by user ID
No a seperate Issue has been created
**Snapshots/Vide
os:**
=> Added graphql query to find direct chats by id[Urgent}

tests/organization.spec.js
testing
Fixes #377 
Yes
No
**Summary**
- To cover tests for all the business logic involved in the process
- It resolves issue #377 
No
Yes
=> test: Modified updateOrganization test

package.json, resolvers/auth_mutations/login.js, resolvers/auth_mutations/signup.js, resolvers/functions/copyToClipboard.js
feature
Fixes #438 
No.
N/A
N/A
**Summary**
- To simplify copying the headers to the clipboard.
- To fix #438 
No.
N/A
Yes
=> Feat: Copy header to clipboard

resolvers/user_mutations/updateUserProfile.js, tests/user_update.spec.js
bugfix
Fixes #442 
Yes
N/A
**Summary**
- To Fix `updateUserProfile` Mutation.
- To resolve #442 
No
N/A
Yes
=> fix: updated updateUserProfile mutation with Tests

resolvers/membership_request_mutations/cancel_membership_request.js
bugfix
Fixes #444 
N/R
N/A
**Summary**
-  To fix `cancelMembershipRequest` mutation.
- To resolve #444 
No.
N/A
Yes
=> Fix: cancelMembership mutation

tests/auth.spec.js, tests/block_user_functionality_tests.spec.js, tests/chats.spec.js, tests/event.spec.js, tests/functions/getToken.js, tests/functions/getUserId.js, tests/language.spec.js, tests/newsfeed.spec.js, tests/organization.spec.js, tests/organizations_connection.spec.js, tests/organizations_member_connection.spec.js, tests/private_organization_membership.spec.js, tests/user_me_query.spec.js, tests/user_organization.spec.js, tests/user_query_with_id.spec.js, tests/user_subqueries.spec.js, tests/user_update.spec.js, tests/users_connection.spec.js
bugfix, testing
Fixes #423 
Yes
- Before fix: 
- After fix:
**Summary**
- To make all tests run in GitHub action.
- Now, tests in GitHub actions work correctly after PR is merged. 
No.
- Tests, when executed per file, are working correctly.
- But when executed combinedly using `npm run test`, many tests fail as there is a signup/login issue.
- The PR fixes this issue. 
Yes
=> fix: To run all tests correctly

locales/en.json, locales/fr.json, locales/hi.json, locales/sp.json, locales/zh.json, src/resolvers/language_maintainer_mutation/addLanguageTranslation.js, src/resolvers/language_maintainer_query/getlanguage.js, src/resolvers/language_mutation/updateLanguage.js, src/resolvers/post_organization_query/organization_post_pagination.js, src/resolvers/user_mutations/updateUserProfile.js
refactoring.
Fixes #467 
N/A
N/A
**Summary**
No.
- To resolve #467 
Yes.
=> fix: throw appropriate errors in api

package-lock.json, src/resolvers/Query.js, src/resolvers/direct_chat_query/directChatsMessagesByChatID.js, src/schema/query.graphql
Added a query to get chat messages of a given chat.
=> Query created for direct chat messages by chat ID

.github/workflows/push.yml
bugfix
Fixes #481 
N/A
N/A
N/A
**Summary**
- To fix Push workflow.
- To resolve #481 
No.
N/A
=> fix: updated push workflow

.github/workflows/push.yml
refactoring
Fixes #
**Summary**
- To Fix Push Workflow Code Coverage.
NO
Yes
=> refactor: Updated Push Workflow

.github/workflows/pull-request.yml
Code cov minor update for including all files
=> code cov yml fix

.github/workflows/pull-request.yml, jest.config.js
Jest will allow access to all js file
=> jest update

tests/resolver_tests/auth_mutations/refresh_token.spec.js, tests/resolver_tests/auth_mutations/revoke_refresh_token_for_user.spec.js
unit-testing
Fixes #475 
**Summary**
- To test refreshToken mutations under auth mutations.
No
Yes
=> Auth unit tests

tests/organization.spec.js
Updated removeOrganization mutation testing
Fixes #378 
yes
**Summary**
No
=> remove organisation mutation tests updated

lib/resolvers/language_maintainer_query/getlanguage.js, tests/resolvers/language_maintainer_query/getlanguage.spec.js
Testing
Fixes #584 
yes
not needed
not needed
**Summary**
no
In the main API the error function is not needed because API language code parameters don't utilize enum but strings which let it throw empty array rather than error
Yes
=> Coverage added to 100% for language query api

lib/resolvers/organization_query/organizations.js, package.json, tests/resolvers/organization_query/organizations.spec.js
Test Coverage
Fixes #587 
Yes
Not needed
Not needed
**Summary**
No
no
=> Coverage 100% for Organisation query

lib/models/Post.js, lib/resolvers/post_mutations/createComment.js, lib/resolvers/post_mutations/likePost.js, lib/resolvers/post_mutations/removeComment.js, lib/resolvers/post_mutations/unlikePost.js, lib/resolvers/post_query/postsByOrganization.js, tests/resolvers/post_query/postsByOrganization.spec.js
Fixes #588
yes
**Summary**
Fixed a bug found on the postsByOrganization query resolver found after writing tests for the issue #588-
=> Fixing issue #588

lib/resolvers/organization_mutations/createOrganization.js, tests/resolver_tests/organization_mutations/createOrganization.spec.js
testing
Fixes #553 
**Summary**
- To write tests for block_user, createOrganization unit testing should be added as it depends on it.
- To resolve #553 
No
Yes
=> test: Added createOrganization Tests and blockUser Tests

lib/resolvers/post_query/post.js, tests/resolvers/post_query/post.spec.js
added 100% test coverage for post query resolver
It's for post query resolver testing
Fixes #591
yes
yes
=> created test for post query

CONTRIBUTING.md
=> Fixed links to Issue Report Guidelines and PR-guidelines

lib/resolvers/post_query/commentsByPost.js
Reverts PalisadoesFoundation/talawa-api#659
Our tests are failing.
- https://github.com/PalisadoesFoundation/talawa-api/runs/5806689541?check_suite_focus=true
=> Revert "Fix commentsByPost"

lib/resolvers/admin_mutations/admin-remove-post.js, tests/resolvers/admin_mutations/admin-remove-post.spec.js
Fixes #564 
Yes
**Summary**
- To address unit testing in admin mutations.
- To Fix #564 
No
Yes
=> test: admin remove post unit tests

lib/resolvers/admin_mutations/admin-remove-event.js, tests/resolvers/admin_mutations/admin-remove-event.spec.js
Fixes #566 
Yes
**Summary**
- To address unit testing in admin mutations.
- To Fix #566 
No.
Yes
=> test: admin remove event mutation unit tests

constants.js, lib/resolvers/membership_request_mutations/accept_membership_request.js, tests/resolvers/membership_request_mutations/accept_membership_request.spec.js
Tests, fixed a bug.
Fixes #576
yes
**Summary**
added tests cases for accept membership request, and fixed some small bugs, changed error output for testing env.
=> added tests for accept_membership_request

lib/resolvers/project_task_mutations/createTask.js, tests/resolvers/event_query/tasksByEvent.spec.js
testing
Fixes #545 
Yes
**Summary**
- To address unit testing in event queries.
- To Fix #545 
No
N/A
Yes
=> test: created tasks by event unit tests

constants.js, lib/resolvers/event_mutations/unregisterForEvent.js, tests/resolvers/event_mutations/unregisterForEvent.spec.js
testing
fixes #516 
Yes
**Summary**
- To address unit testing in unregister event mutations.
- To fix #516 
No
N/A
Yes
=> test: unregister for event mutation tests

tests/resolvers/event_query/registeredEventsByUser.spec.js
testing
fixes #541 
Yes
**Summary**
- To address unit testing in registered events by user query.
- To fix #541 
No
N/A
Yes
=> test: added registered events user query tests

constants.js, lib/helper_functions/organizationExists.js, lib/helper_functions/userExists.js, lib/resolvers/admin_mutations/removeAdmin.js, lib/resolvers/direct_chat_mutations/sendMessageToDirectChat.js, lib/resolvers/direct_chat_query/directChatsMessagesByChatID.js, lib/resolvers/functions/adminCheck.js, lib/resolvers/functions/creatorCheck.js, lib/resolvers/group_chat_mutations/addUserToGroupChat.js, lib/resolvers/group_chat_mutations/sendMessageToGroupChat.js, lib/resolvers/organization_mutations/updateOrganization.js, lib/resolvers/user_query/myLanguage.js, lib/resolvers/user_query/userLanguage.js, tests/resolvers/admin_mutations/removeAdmin.spec.js, tests/resolvers/direct_chat_mutations/sendMessageToDirectChat.spec.js, tests/resolvers/direct_chat_query/chatsbychatID.spec.js, tests/resolvers/direct_chat_query/directChatMessages.spec.js, tests/resolvers/direct_chat_query/directChatsMessagesByChatID.spec.js, tests/resolvers/group_chat_mutations/addUserToGroupChat.spec.js, tests/resolvers/group_chat_mutations/sendMessageToGroupChat.spec.js, tests/resolvers/membership_request_mutations/accept_membership_request.spec.js, tests/resolvers/organization_mutations/updateOrganization.spec.js, tests/resolvers/user_query/myLanguage.spec.js, tests/resolvers/user_query/userLanguage.spec.js
Fixes #567 
Yes
**Summary**
- To address unit testing in admin mutations.
- To Fix #567 
No
- Other files have been added to PR due to npm run lint.
Yes
=> test: Remove admin Mutation unit tests

constants.js, lib/resolvers/admin_mutations/admin-remove-group-chat.js, tests/resolvers/admin_mutations/admin-remove-group-chat.spec.js
Fixes #565 
Yes
**Summary**
- To address unit testing in admin mutations.
- To Fix #565 
No.
Yes
=> test: admin remove group chat unit tests

lib/models/Event.js, tests/resolvers/event_query/eventsByOrganization.spec.js
testing
fixes #539 
Yes
**Summary**
- To address unit testing in events by organization query. 
- To fix #539 
No
N/A
Yes
=> tests: events by organization tests

constants.js, lib/models/Event.js, lib/resolvers/event_query/isUserRegister.js, tests/resolvers/event_query/isUserRegister.spec.js
testing
fixes #540 
Yes
**Summary**
- To address unit testing in user register event query. 
- To fix #540 
No
N/A
Yes
=> test: user register event tests

constants.js, lib/models/Event.js, lib/resolvers/event_mutations/registerForEvent.js, tests/resolvers/event_mutations/registerForEvent.spec.js
unit-testing
Fixes #514
Yes
**Summary**
- To fix issue #514 
- To cover the unit testing for event resolvers
No
The Max coverage for this file has been achieved. 
Yes
=> test: register event mutation unit tests

lib/resolvers/auth_mutations/login.js, tests/resolver_tests/auth_mutations/login.spec.js
Fixes #706
This PR will fix login/signup issue in the Talawa mobile application.
=> populate user fields on login to avoid null error

tests/resolvers/group_chat_query/groupChatMessages.spec.js
Test Case #593 
Fixes #593 
Yes
**Summary** : 
This test just makes sure that the function is returning a valid JSON Object
No
Yes
=> [Code Coverage ] Test : groupChatMessages.js

lib/models/Event.js, lib/schema/event/event.graphql
Add event coordinates.
Fixes: #721 
Does this PR introduce a breaking change?
No
Other information
This pull request is under GSoC'22.
Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?
Yes
=> add event location

.env.sample, .gitignore, INSTALLATION.md, firebaseOptions.js, lib/models/User.js, lib/resolvers/Mutation.js, lib/resolvers/auth_mutations/login.js, lib/resolvers/auth_mutations/logout.js, lib/resolvers/auth_mutations/saveFcmToken.js, lib/resolvers/event_mutations/createEvent.js, lib/schema/mutation.graphql, lib/schema/user/auth.graphql, package-lock.json, package.json
New mutation for logout
Create notification on new event
feature
Fixes #720 
No.
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md).**
Yes
=> Add firebase-admin

lib/resolvers/auth_mutations/login.js, lib/schema/user/auth.graphql, package-lock.json, package.json
Remove token field from LoginInput. No longer required as we are getting it from saveFcmToken query.
Fixes #736
=> remove token

.env.sample, .github/workflows/pull-request.yml, .gitignore, INSTALLATION.md, firebaseOptions.js, lib/ConnectionManager/addTenantConnection.js, lib/ConnectionManager/connections.js, lib/ConnectionManager/destroyConnections.js, lib/ConnectionManager/getTenantConnection.js, lib/ConnectionManager/index.js, lib/ConnectionManager/initTenants.js, lib/helper_functions/addTenantId.js, lib/helper_functions/getTenantFromId.js, lib/models/Tenant.js, lib/models/User.js, lib/resolvers/Mutation.js, lib/resolvers/auth_mutations/login.js, lib/resolvers/auth_mutations/logout.js, lib/resolvers/auth_mutations/saveFcmToken.js, lib/resolvers/event_mutations/createEvent.js, lib/schema/mutation.graphql, lib/schema/user/auth.graphql, package-lock.json, package.json, tests/database/multi-tenancy.spec.js
feature
Yes
**Summary**
finished the connection manager that is used in the multi-tenancy project of GSoC 2022
=> added connection manager

lib/resolvers/membership_request_mutations/reject_membership_request.js, tests/resolvers/membership_request_mutations/reject_membership_request.spec.js
Test
Fixes #577
No
Not relevant
**Summary**
This contains test for reject_membership_request.js
No breaking change
no other infirmation
Yes
=> Test for reject_membership_request.js

package-lock.json, package.json
Removed the package named easygraphql-tester
bugfix
Fixes #707
-
-
-
**Summary**
Removed the package named easygraphql-tester because it was not being used anywhere in the app and had a security vulnerability.
No
-
Yes
=> Removed package easygraphql-tester

package-lock.json, package.json
Reverts PalisadoesFoundation/talawa-api#747
We are getting the following messages when trying to deploy the code on the Heroku server.  Please fix.
```
-----> Building on the Heroku-20 stack
-----> Using buildpack: heroku/nodejs
-----> Node.js app detected
-----> Creating runtime environment
NPM_CONFIG_LOGLEVEL=error
NODE_VERBOSE=false
NODE_ENV=production
NODE_MODULES_CACHE=true
-----> Installing binaries
engines.node (package.json):  unspecified
engines.npm (package.json):   unspecified (use default)
Resolving node version 16.x...
Downloading and installing node 16.17.0...
Using default npm version: 8.15.0
-----> Restoring cache
- npm cache
-----> Installing dependencies
Installing node modules
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your …
```
=> Revert "Removed package easygraphql-tester"

lib/directives/authDirective.js, lib/directives/roleDirective.js, lib/helper_functions/auth.js, lib/helper_functions/deleteDuplicatedImage.js, lib/helper_functions/deleteImage.js, lib/helper_functions/imageAlreadyInDbCheck.js, lib/helper_functions/imageExtensionCheck.js, lib/models/Chat.js, lib/models/Comment.js, lib/models/DirectChat.js, lib/models/DirectChatMessage.js, lib/models/Donation.js, lib/models/Event.js, lib/models/EventProject.js, lib/models/File.js, lib/models/Group.js, lib/models/GroupChat.js
Documentation
Yes
**Summary**
Added JSDoc comments to the following folders:
```
- lib/directives
- lib/helper_functions
```
Yes
=> Documentation

lib/helper_functions/ReuploadDuplicateCheck.js, lib/helper_functions/mailer.js, lib/helper_functions/organizationExists.js, lib/helper_functions/uploadImage.js, lib/helper_functions/userExists.js, lib/middleware/is-auth.js, lib/models/GroupChatMessage.js, lib/models/ImageHash.js, lib/models/Language.js, lib/models/MembershipRequest.js, lib/models/Message.js, lib/models/Organization.js, lib/models/Plugin.js, lib/models/PluginsField.js, lib/models/Post.js, lib/models/Task.js, lib/models/User.js
Documentation
Yes
**Summary**
Documentation for:
- `lib/helper_functions/ReuploadDuplicateCheck.js`
- `lib/helper_functions/mailer.js`
- `lib/helper_functions/organizationExists.js`
- `lib/helper_functions/uploadImage.js`
- `lib/helper_functions/userExists.js`
- `lib/middleware/is-auth.js`
- `lib/models/GroupChatMessage.js`
- `lib/models/ImageHash.js`
- `lib/models/Language.js`
- `lib/models/MembershipRequest.js`
- `lib/models/Message.js`
- `lib/models/Organization.js`
- `lib/models/Plugin.js`
- `lib/models/PluginsField.js`
- `lib/models/Post.js`
- `lib/models/Task.js`
- `lib/models/User.js`
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUT …
=> [documentation] : lib/helper_functions, lib/middlewares, lib/models

src/lib/middleware/isAuth.ts, src/lib/models/GroupChatMessage.ts, src/lib/models/ImageHash.ts, src/lib/models/Language.ts, src/lib/models/MembershipRequest.ts, src/lib/models/Message.ts, src/lib/models/MessageChat.ts, src/lib/models/Organization.ts, src/lib/models/Plugin.ts, src/lib/models/PluginField.ts, src/lib/models/Post.ts, src/lib/models/Task.ts, src/lib/models/User.ts, src/lib/utilities/adminCheck.ts, src/lib/utilities/copyToClipboard.ts, src/lib/utilities/mailer.ts, src/lib/utilities/reuploadDuplicateCheck.ts, src/lib/utilities/uploadImage.ts
Documentation
Yes
**Summary**
Documentation for:
- `lib/helper_functions/ReuploadDuplicateCheck.js`
- `lib/helper_functions/mailer.js`
- `lib/helper_functions/organizationExists.js`
- `lib/helper_functions/uploadImage.js`
- `lib/helper_functions/userExists.js`
- `lib/middleware/is-auth.js`
- `lib/models/GroupChatMessage.js`
- `lib/models/ImageHash.js`
- `lib/models/Language.js`
- `lib/models/MembershipRequest.js`
- `lib/models/Message.js`
- `lib/models/Organization.js`
- `lib/models/Plugin.js`
- `lib/models/PluginsField.js`
- `lib/models/Post.js`
- `lib/models/Task.js`
- `lib/models/User.js`
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUT …
=> [documentation] : utilities, middleware, models

src/lib/models/Comment.ts, src/lib/models/DirectChat.ts, src/lib/models/DirectChatMessage.ts, src/lib/models/Donation.ts, src/lib/models/Event.ts, src/lib/models/EventProject.ts, src/lib/models/File.ts, src/lib/models/Group.ts, src/lib/models/GroupChat.ts, src/lib/models/MessageChat.ts
Documentation
**Summary**
Added TsDoc comments to the following folder:
```
- src/lib/models
```
Yes
=> Typescript docs models

src/lib/typeDefs/chats/chat.ts, src/lib/typeDefs/chats/message.ts, src/lib/typeDefs/plugin/plugin.ts, src/lib/typeDefs/plugin/pluginField.ts, src/lib/typeDefs/user/auth.ts, src/lib/typeDefs/user/user.ts
Documentation
**Summary**
Added TsDoc comments to the following folder:
```
- src/lib/typedefs
```
Yes
=> [Documentation] : src/typedefs folder

INSTALLATION.md
A grammatical error in `INSTALLATION.md`
Fixes #817 
**Summary**
=> fix grammatical error in INSTALLATION.md

__tests__/resolvers/Mutation/createMessageChat.spec.ts
Increases code coverage to 100% for `createMessageChat.ts`
Fixes #814 
**Summary**
No
Yes
=> Increase Code coverage for createMessageChat.ts

__tests__/resolvers/Mutation/removeDirectChat.spec.ts
Increases code coverage to 100% for `removeDirectChat.ts`
Fixes #809 
**Summary**
No
Yes
=> Increase code coverage for removeDirectChat.ts

vite.config.ts
Fix 
Fixes #824 
Not required
Not required
**Summary**
Removed `index.ts` files from ignore statements
No
=> Remove ignore for `index.ts` files

__tests__/resolvers/Organization/creator.spec.ts, __tests__/resolvers/Organization/index.spec.ts
Increases code coverage to 100% for `creator.ts` and adds unit test for `Organization/index.ts`.
Fixes #808 
**Summary**
No
Yes
=> Increases code coverage for resolvers/Organization

__tests__/resolvers/DirectChat/index.spec.ts
Increases code coverage to 100% for  `DirectChat/index.ts`
Fixes #810 
**Summary**
No
Yes
=> Increase code coverage for DirectChat/index.ts

package-lock.json, package.json
Fixed a bug by upgrading jsonwebtoken to 9.0.0
Fixes #829 
No
Not required
Not required
No
Yes
=> Bump jsonwebtoken from 8.5.1 to 9.0.0

__tests__/middleware/isAuth.spec.ts
Adds tests for `middleware/isAuth.ts`
Fixes #801 
**Summary**
No
Yes
=> Add tests for middleware/isAuth.ts

__tests__/resolvers/DirectChatMessage/index.spec.ts
Increases code coverage for `resolvers/DirectChatMessage`
Fixes #804 
**Summary**
No
Yes
=> Adds test for DirectChatMessage/index.ts

__tests__/resolvers/GroupChat/index.spec.ts, package-lock.json, package.json
Fixed a bug by upgrading marked to 4.0.10
Fixes #834 
No
Not required
Not required
No
Yes
=> Bump marked to 4.0.10

__tests__/resolvers/MembershipRequest/index.spec.ts
Increases code coverage for `resolvers/MembershipRequest/index.ts` to 100%
Fixes #807 
**Summary**
No
Yes
=> Increase code coverage for resolvers/MembershipRequest/index.ts

package-lock.json, setup/utils/displayMarkdown.js
Bugfix
Fixes #845 
No
Not relevant
No
Not required
Yes
=> Bug fixed to display markdown using marked

__tests__/resolvers/GroupChatMessage/index.spec.ts
Adds test for `resolvers/GroupChatMessage/index.ts`
Fixes #806 
**Summary**
No
Yes
=> Adds test for GroupChatMessage/index.ts

package-lock.json, setup/utils/displayMarkdown.js
Bugfix
Fixes #845 
No
Not relevant
No
Not required
Yes
=> Re-Bug fixed to display markdown using marked

__tests__/utilities/mailer.spec.ts
Adds test for `utilities/mailer.ts`
Fixes #800 
**Summary**
No
Yes
=> Adds test for utilities/mailer.ts

__tests__/utilities/adminCheck.spec.ts
Adds test for `utilities/adminCheck.ts`.
Fixes #555 
**Summary**
No
Yes
=> Adds test for utilities/adminCheck

INSTALLATION.md
Docs fix.
Fixes #
No
-
Yes
**Summary**
A small fix to INSTALLATION.md
No
-
Yes
=> updated INSTALLATION.md

__tests__/resolvers/Query/users.spec.ts
Increases code coverage for `resolvers/Query/users.ts` to 100%.
Fixes #547 
**Summary**
No
Yes
=> Increases code coverage for Query/users

tests/resolvers/Mutation/updateEventProject.spec.ts
Adding tests
Fixes #898
YES 
**Summary**
YES
=> Added tests for src/resolvers/Mutation/updateEventProject.ts

INSTALLATION.md
Docs fix
Fixes #
No
-
-
**Summary**
Changed installation script for packages from `npm run install` to `npm install` in INSTALLATION.md.
-
-
Yes
=> fixed package installation script in INSTALLATION.md

tests/resolvers/Mutation/createPost.spec.ts
Tests for createPost.ts
Fixes #905 
Yes
**Summary**
Yes
=> Add tests for src/lib/resolvers/Mutation/createPost.ts

tests/resolvers/Mutation/createDirectChat.spec.ts
🧪 **What kind of change does this PR introduce?**
This pull request is to include a comprehensive test for the createDirectChat.js file, which will ensure its proper functionality and performance before it is integrated into the main codebase.
🧪 **Issue Number:**
Fixes #572
Yes
🧪**Snapshots/Vid**
🧪 **If relevant, did you update the documentation?**
🧪**Summary**
Adding test for createDirectChat.spec.ts
🧪 **Does this PR introduce a breaking change?**
🧪 **Other information**
🧪 **Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes
=> test: adding test for createDirectChat.ts

src/resolvers/Mutation/createOrganization.ts, src/typeDefs/organization.ts, src/types/generatedGraphQLTypes.ts
In the admin homepage, the icon of an organisation isn’t rendered properly. I had raised this issue in the talawa-admin repository. It seems there were some errors to be solved from the backend as well. This PR contains all the necessary changes for the icon to be rendered properly/
No.
There were just few modifications and minor errors to be rectified. I haven’t written any tests. Although all the tests are running successfully and the application produces the necessary result.
Admin page before : -
Admin page now : -
Test coverage after PR : -
https://user-images.githubusercontent.com/92572013/213864603-fcac948b-de3f-46c5-8f5d-39d52f1862c5.mp4
No
The motivation for solving this challenge was the user experience, as the site looks very unprofessional and broken when organisation's icons …
=> [fix] : organisation icon rendering fixed in backend

tests/resolvers/Mutation/joinPublicOrganization.spec.ts
🧪 **What kind of change does this PR introduce?**
This pull request is to include a comprehensive test for the joinpublicorganization.ts file, which will ensure its proper functionality and performance before it is integrated into the main codebase.
🧪 **Issue Number:**
Fixes #538 
Yes
🧪**Snapshots/Vid**
🧪 **If relevant, did you update the documentation?**
🧪**Summary**
Adding test for  joinpublicorganization.ts
🧪 **Does this PR introduce a breaking change?**
🧪 **Other information**
🧪 **Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes
=> test : adding test for joinpublicorganization.ts

tests/resolvers/Mutation/createPost.spec.ts, tests/resolvers/Mutation/refreshToken.spec.ts
Fixes #902 
Yes
**Summary**
Yes
=> Added tests for src/lib/resolvers/Mutation/refreshToken.ts

src/resolvers/Mutation/updatePluginInstalledOrgs.ts, tests/resolvers/Mutation/updatePluginInstalledOrgs.spec.ts
Test + bugfix
Fixes #897 
Yes
**Summary**
No.
Yes
=> Added tests for `src/lib/resolvers/Mutation/updatePluginInstalledOrgs.ts`

tests/resolvers/Mutation/index.spec.ts
🧪 **What kind of change does this PR introduce?**
This pull request is to include a comprehensive test for the Mutation -> index.ts file, which will ensure its proper functionality and performance before it is integrated into the main codebase.
🧪 **Issue Number:**
Fixes #904  
Yes
🧪**Snapshots/Vid**
🧪 **If relevant, did you update the documentation?**
🧪**Summary**
Adding test for Mutation -> index.ts
🧪 **Does this PR introduce a breaking change?**
🧪 **Other information**
🧪 **Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes
=> test: adding test for Mutation -> index.ts

tests/utilities/uploadImage.spec.ts
Fixes #947 947
Yes
**Summary**
Yes
=> urgent bugFix

tests/resolvers/Mutation/signUp.spec.ts
🧪 **What kind of change does this PR introduce?**
This pull request is to include a comprehensive test for the signUp.ts file, which will ensure its proper functionality and performance before it is integrated into the main codebase.
🧪 **Issue Number:**
Fixes #899 
Yes
🧪**Snapshots/Vid**
🧪 **If relevant, did you update the documentation?**
🧪**Summary**
Adding test for signUp.ts
🧪 **Does this PR introduce a breaking change?**
🧪 **Other information**
🧪 **Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?**
Yes
=> test: adding test for signUp.ts

tests/libraries/errors/unauthenticatedError.spec.ts
Test
Fixes #916 
**Summary**
https://github.com/PalisadoesFoundation/talawa-api/issues/916 
Created a folder structure in tests folder for writing tests for files in libraries/errors. Desired tests are written in unauthenticatedError.spec.ts
Yes
=> Test written for unauthenticatedError.ts 

src/utilities/deleteImage.ts, tests/utilities/deleteImage.spec.ts, tests/utilities/uploadImage.spec.ts
Fixes #888 
Yes
**Summary**
Yes.
=>  test for `src/utilities/deleteImage.ts`

tests/helpers/userAndOrg.ts, tests/resolvers/Organization/admins.spec.ts, tests/resolvers/Organization/blockedUsers.spec.ts, tests/resolvers/Organization/creator.spec.ts, tests/resolvers/Organization/members.spec.ts, tests/resolvers/Organization/membershipRequests.spec.ts
Feature
Fixes part of #961
Yes
**Summary**
Migrated the Organization tests to use helper functions.
No
The maintainers can review the helpers added and all the tests in the `Organization` category and recommend other functions with may help to reduce duplication. Then we can start migrating these helpers to other tests.
Yes
=> Add helper functions for testing

tests/helpers/groupChat.ts, tests/resolvers/GroupChatMessage/groupChatMessageBelongsTo.spec.ts, tests/resolvers/GroupChatMessage/sender.spec.ts
Feature
Fixes #969 
Yes
NA
**Summary**
Migrate the tests as described in the parent issue
Yes
=> Migrate tests for GroupChatMessage

tests/helpers/directChat.ts, tests/resolvers/DirectChat/creator.spec.ts, tests/resolvers/DirectChat/messages.spec.ts, tests/resolvers/DirectChat/organization.spec.ts, tests/resolvers/DirectChat/users.spec.ts
Feature
Fixes #966 
Yes
No
Migrated the relevant tests.
Yes
=> Migrate tests in DirectChat

src/resolvers/Subscription/directMessageChat.ts, tests/resolvers/Subscription/directMessageChat.spec.ts
Fixes #892 
Yes
**Summary**
No
Yes
=> Test for `src/resolvers/Subscription/directMessageChat.ts`

tests/helpers/events.ts, tests/helpers/membershipRequests.ts, tests/helpers/posts.ts, tests/helpers/userAndOrg.ts, tests/resolvers/Mutation/acceptAdmin.spec.ts, tests/resolvers/Mutation/acceptMembershipRequest.spec.ts, tests/resolvers/Mutation/addOrganizationImage.spec.ts, tests/resolvers/Mutation/addUserImage.spec.ts, tests/resolvers/Mutation/addUserToGroupChat.spec.ts, tests/resolvers/Mutation/adminRemoveEvent.spec.ts, tests/resolvers/Mutation/adminRemoveGroup.spec.ts, tests/resolvers/Mutation/adminRemovePost.spec.ts, tests/resolvers/Mutation/blockPluginCreationBySuperadmin.spec.ts, tests/resolvers/Mutation/blockUser.spec.ts, tests/resolvers/Mutation/cancelMembershipRequest.spec.ts, tests/resolvers/Mutation/createAdmin.spec.ts, tests/resolvers/Mutation/createComment.spec.ts, tests/resolvers/Mutation/createDirectChat.spec.ts, tests/resolvers/Mutation/createDonation.spec.ts, tests/resolvers/Mutation/createEvent.spec.ts, tests/resolvers/Mutation/createEventProject.spec.ts, tests/resolvers/Mutation/createGroupChat.spec.ts
Refactors tests to use helper function as introduced in #961 
Fixes part of #971 
Yes
NA
**Summary**
Migrated tests and created helper files as needed.
No
Yes
=> Migrate tests to use helpers

.github/workflows/pull-request.yml
What kind of change does this PR introduce?
Issue Number:
Fixes https://github.com/PalisadoesFoundation/talawa-api/issues/1017
Did you add tests for your changes?
Yes
Snapshots/Videos:
If relevant, did you update the documentation?
No, there was no need to update the documentation
Summary
This wasn't any check for type-checking the variables in the ci/cd pipeline which is essential as typescript is a hard typed language.
Does this PR introduce a breaking change?
No
Other information
Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?
Yes
=> adds check for typecheck in github actions

src/resolvers/Mutation/createEvent.ts, tests/resolvers/Mutation/createEvent.spec.ts
Fixes #908 
Yes
**Summary**
Yes
=> Test for `src/resolvers/Mutations/createEvent.ts`

src/utilities/creatorCheck.ts, tests/utilities/creatorCheck.spec.ts
Fixes #1029 
Yes
**Summary**
Yes
=> Tests for `src/utilities/creatorCheck.ts`

tests/resolvers/MembershipRequest/organization.spec.ts, tests/resolvers/MembershipRequest/user.spec.ts
refactoring and using helper function in membership-request
Fixes #970 
yes
**Summary**
=> Fix #970 :  Refactor: tests/resolvers/MembershipRequest

src/resolvers/Mutation/updateTask.ts, tests/resolvers/Mutation/updateTask.spec.ts
=> Tests for `src/resolvers/Mutation/updateTask.ts`

.husky/pre-commit, CONTRIBUTING.md, INSTALLATION.md, package-lock.json, package.json
Feature: Add and configure Husky
Fixes #1027 
Yes
Sample terminal screenshots after using Husky
Yes
**Summary**
Added Husky to the code base, and configured it to run all the formatting, linting and type checking scripts on commits. Updated documentation about the same, and also added how to opt out of it.
No
NA
Yes
=> Add Husky to improve developer experience [Fixes #1027]

src/typeDefs/index.ts
bugfix
Fixes #1062
No
Before fix
After fix
-
**Summary**
The `dev` script was failing because of some empty document nodes in typeDefs. So, commented them out until they're used some time in the future.
Merging of this PR is urgently required.
Yes
=> fixed graphql schema parse error

src/directives/roleDirective.ts, src/resolvers/Mutation/acceptAdmin.ts, src/resolvers/Mutation/createOrganization.ts, src/typeDefs/mutations.ts, src/utilities/index.ts, src/utilities/superAdminCheck.ts, tests/resolvers/Mutation/acceptAdmin.spec.ts, tests/resolvers/Mutation/createOrganization.spec.ts, tests/utilities/superAdminCheck.spec.ts
Bug Fix 
Fixes #1061 
Yes
Now if a user with userType other than "SUPERADMIN" makes a request to create an organization, then it throws un authorised error
I changed my user role to SUPERADMIN later to make sure I can still create an organization after that and yes it works.
**Summary**
Yes
=> Create org security bug fix

src/constants.ts, src/libraries/errors/index.ts, src/libraries/errors/inputValidationError.ts, src/libraries/validators/compareDates.ts, src/libraries/validators/validatePassword.ts, src/libraries/validators/validateString.ts, src/resolvers/Mutation/createEvent.ts, src/resolvers/Mutation/createOrganization.ts, src/resolvers/Mutation/createPost.ts, src/resolvers/Mutation/signUp.ts, src/resolvers/Mutation/updateEvent.ts, src/resolvers/Mutation/updatePost.ts, tests/resolvers/Mutation/createEvent.spec.ts, tests/resolvers/Mutation/createOrganization.spec.ts, tests/resolvers/Mutation/createPost.spec.ts, tests/resolvers/Mutation/updateEvent.spec.ts, tests/resolvers/Mutation/updatePost.spec.ts
Previously, the ```createPost``` ```updatePost``` ```createEvent``` ```updateEvent``` ```createOrganization``` Resolvers were not having a input validation, so a potential attacker could buffer overflow the database and reduce it performance by submitting data of vary large length.
This PR adds the input validators so that input can be checked before adding that data to the database, and also throws meaning full errors to the user.
Fixes #1064 
Yes
(Check for error in the below screenshots, when a user enters invalid data.
.
.
.
Same validation goes for add and update event and create organization.
.
Not Required …
=> Integrated input validation in ```createPost``` ```updatePost``` ```createEvent``` ```updateEvent``` ```createOrganization``` resolvers

src/constants.ts, src/utilities/imageAlreadyInDbCheck.ts, src/utilities/imageExtensionCheck.ts, tests/utilities/imageAlreadyInDbCheck.spec.ts, tests/utilities/imageExtensionCheck.spec.ts
Separated the Hardcoded errors in the files located in src/utilities into constant objects.
Fixes #1040 
not required
**Summary**
Separated the Hardcoded errors in the files located in src/utilities into constant objects.
no
no
yes
=> fixes: #1040 addded constants for src/utilities files

backend-api-documentation.md, src/resolvers/Query/eventsByOrganizationConnection.ts, src/resolvers/Query/getDonationByOrgIdConnection.ts, src/resolvers/Query/index.ts, src/resolvers/Query/organizationsMemberConnection.ts, src/resolvers/Query/postsByOrganizationConnection.ts, src/typeDefs/inputs.ts, src/typeDefs/queries.ts, src/types/generatedGraphQLTypes.ts, tests/resolvers/Query/organizationsMemberConnection.spec.ts, tests/resolvers/Query/postsByOrganizationConnection.spec.ts
Create query resolver filters for search filters.
Fixes #1052 
Partially added.
Yes, [talawa-admin-issue-460](https://github.com/PalisadoesFoundation/talawa-admin/issues/460) should be simultaneously fixed.
Yes
=> Create query resolvers for search filters

src/constants.ts, src/resolvers/Mutation/removeMember.ts, src/typeDefs/inputs.ts, src/typeDefs/mutations.ts, src/types/generatedGraphQLTypes.ts, tests/resolvers/Mutation/removeMember.spec.ts
Bug Fix
Fixes #1076 
Yes
// successfully deletes a user in the admin portal
// custom error displayed on the client side from the server(works for all other test cases)
**Summary**
Now removing the user works perfectly in the backend with appropriate error also one change I made was - to change the `removeMember` function to individual removal instead of bulk removal due to reasons explained here-
https://thepalisadoes-dyb6419.slack.com/archives/C01RPC00K0D/p1676919304352869?thread_ts=1676916553.031469&cid=C01RPC00K0D
**Have you read the …
=> Remove Member Bug Fix 

.eslintrc.json, src/utilities/imageAlreadyInDbCheck.ts, src/utilities/imageExtensionCheck.ts
This adds the necessary checks to the .eslintrc.json file to check if any code file is using the src import from their parent folder.
Fixes #1083 
Not Required
Not Relevant
Not Required.
**Summary**
This PR adds the necessary changes to the eslint configuration file which will help in detecting the improper import statements inside the code files. 2 such files are fixed in this PR.
No.
No.
Yes.
=> Fix eslint to check for improper import statements [Fixes #1083]

src/utilities/creatorCheck.ts, tests/resolvers/Mutation/removeAdmin.spec.ts, tests/resolvers/Mutation/removeOrganization.spec.ts, tests/utilities/creatorCheck.spec.ts
This PR refactors tests in `tests/utilities` folder and fixes some mutation test related to it.
Fixes #1004  
Fixes #993 
Yes
N.A.
Yes
=> Refactor: tests/utilities folder [Fixes: #1004 & #993 ]

src/libraries/requestContext.ts, tests/libraries/requestContext.spec.ts
This Pull Request includes tests written for file `src/libraries/requestContext.ts`. The testcases are covered for `cls-hooked` functionality as well as `i18n`. 
**Issue Number:** #914 
**Did you add tests for your changes?  Yes** 
The code coverage obtained is 100%.
Certain code blocks in `requestContext.ts` are not utilized in the application but they do return expected behavior. Fixes are still required accordingly but these code blocks are not modified but tests are included for return values and errors in this PR
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?** Yes
=> tests for 'src/libraries/requestContext.ts'

src/libraries/errors/index.ts, src/libraries/errors/invalidFileTypeError.ts, src/models/EncodedImage.ts, src/resolvers/Mutation/createOrganization.ts, src/server.ts, src/typeDefs/mutations.ts, src/types/generatedGraphQLTypes.ts, src/utilities/encodedImageStorage/encodedImageExtensionCheck.ts, src/utilities/encodedImageStorage/uploadEncodedImage.ts, tests/resolvers/Mutation/createOrganization.spec.ts, tests/utilities/encodedImageStorage/encodedImageExtensionCheck.spec.ts, tests/utilities/encodedImageStorage/uploadEncodedImage.spec.ts
bugFix
Fixes #1080
Not right now
**Summary**
Yes
=> Encoded Image uploads and retrieval

CONTRIBUTING.md
Enhancement
Fixes #1058 
Yes
**Summary**
Added info about GraphQL playground
No
yes
=> Add/GraphQL Guide in Talawa-API

src/models/Event.ts
Bugfix
Fixes part of #1101 
Must be merged with [this PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/523) to restore the functionality
NA
NA
NA
**Summary**
Updated the `endDate`, `startDate`, `endTime` and `startTime` variables to be stored as Date type in the database (and not String) so that they can be serialized correctly by `GraphQL-Scalars`
This code has been tested with talawa-mobile's create event functionality too. 
No
NA
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master …
=> Change the data type of storage of attributes of Event Model [Fixes part of #1101]

src/libraries/requestTracing.ts, tests/libraries/requestTracing.spec.ts
This Pull Request provides testing for file `src/lib/libraries/requestTracing.ts`. We test for getTracingID, setTracingID functions, and `requestTracing middleware`.
Fixes #913 
**Did you add tests for your changes? : Yes**
We receive 100% code coverage covering all the possible testcases
**Does this PR introduce a breaking change? No**
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?  Yes**
=> tests for `src/lib/libraries/requestTracing.ts`

src/resolvers/Subscription/messageSentToDirectChat.ts, tests/resolvers/Subscription/messageSentToDirectChat.spec.ts
This Pull Request provides testing for the file `src/lib/resolvers/Subscription/messageSentToDirectChat.ts`. We have tested for Direct Chat message subscription under different cases.
Fixes #890 
**Did you add tests for your changes? Yes**
The code coverage obtained is 100% with alternative testcases considered.
**Does this PR introduce a breaking change? No**
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)? Yes**
=> tests for `src/lib/resolvers/Subscription/messageSentToDirectChat.ts`

src/models/Organization.ts, src/resolvers/Mutation/createOrganization.ts, src/typeDefs/inputs.ts, src/typeDefs/types.ts, src/types/generatedGraphQLTypes.ts, tests/resolvers/Mutation/createOrganization.spec.ts
Feature Update 
Fixes #1118 
Yes
NA
Will update after this functionality is merged
**Summary**
Removed the support for tags for Organziation Model and migrated all the relevant files.
Yes
Must be merged alongside the corresponding [PR in Admin Panel](https://github.com/PalisadoesFoundation/talawa-admin/pull/532)
NA
Yes
=> Remove tags for Organization

src/constants.ts, src/models/EncodedImage.ts, src/resolvers/Mutation/addOrganizationImage.ts, src/resolvers/Mutation/addUserImage.ts, src/resolvers/Mutation/createOrganization.ts, src/resolvers/Mutation/createPost.ts, src/resolvers/Mutation/signUp.ts, src/resolvers/Mutation/updateUserProfile.ts, src/typeDefs/mutations.ts, src/types/generatedGraphQLTypes.ts, src/utilities/encodedImageStorage/deletePreviousImage.ts, src/utilities/encodedImageStorage/uploadEncodedImage.ts, tests/resolvers/Mutation/addOrganizationImage.spec.ts, tests/resolvers/Mutation/addUserImage.spec.ts, tests/resolvers/Mutation/createPost.spec.ts, tests/resolvers/Mutation/signUp.spec.ts, tests/resolvers/Mutation/updateUserProfile.spec.ts, tests/utilities/encodedImageStorage/deletePreviousImage.spec.ts, tests/utilities/encodedImageStorage/uploadEncodedImage.spec.ts
This PR will introduce the following change:
Optimise the reupload logic for multiple reuploads ,
Delete Image Function
Apply upload Image function wherever necessary.
Add the tests for 2. and 3.
Fixes #1111
Partially.
**Summary**
No.
Yes
=> Encode image Solution

.eslintrc.json, src/typeDefs/inputs.ts, src/types/generatedGraphQLTypes.ts
This PR adds the ```location``` field to input of updateOrg mutation.
Linked issue: https://github.com/PalisadoesFoundation/talawa-admin/issues/531
Fixes #1125 
Not required
Not required
Not required
**Summary**
This PR adds the ```location``` field to input of updateOrg mutation.
No
No
Yes
=> TypeDefs changes for updateOrg feature to work [Fixes #1125]

.eslintrc.json, src/constants.ts, src/libraries/validators/validateString.ts, src/resolvers/Mutation/createEvent.ts, src/resolvers/Mutation/createOrganization.ts, src/resolvers/Mutation/createPost.ts, src/resolvers/Mutation/updateEvent.ts, src/resolvers/Mutation/updatePost.ts, tests/resolvers/Mutation/createEvent.spec.ts, tests/resolvers/Mutation/createOrganization.spec.ts, tests/resolvers/Mutation/createPost.spec.ts, tests/resolvers/Mutation/updateEvent.spec.ts, tests/resolvers/Mutation/updatePost.spec.ts
This PR removes the un-necessary regex checks which if present could interfere with i18n inputs.
Fixes #1116 
Yes
Not required
Not required
**Summary**
This PR removes the un-necessary regex checks which if present could interfere with i18n inputs.
No
No
Yes
=> Remove regex validations for i18n inputs to work [Fixes #1116]

.husky/post-merge, CONTRIBUTING.md
a bugfix
#1108 
Fixes #
no
not required
Yes
**Summary**
This PR will improve user experience. Now whenever some made a PR with some changes to the pakage.json, if any other person will pull those files to his local system, he will automatically get the latest dependencies and hence closes #1108 
No
=> added post merge hook using husky

.env.sample, INSTALLATION.md
This PR created the new LAST_RESORT_SUPERADMIN_EMAIL parameter. The description of what it does needs to be clearer.
- https://github.com/PalisadoesFoundation/talawa-api/pull/1120
Fixes #1144
- N/A
- N/A
**Summary**
- N/A
- N/A
Yes
=> Update documentation about the LAST_RESORT_SUPERADMIN_EMAIL parameter

.github/workflows/pull-request.yml, .github/workflows/push.yml
Our [push.yml](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/push.yml) and [pull-request.yml](https://github.com/PalisadoesFoundation/talawa-api/blob/develop/.github/workflows/pull-request.yml) files use hard coded values for these environment variables for our tests to pass successfully.
This PR generates them on the fly, without replying on Secrets.
Fixes #485
Not Needed
Not Required
Not Required
No
No
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTR …
=> Dynamic Generation of ```ACCESS_TOKEN_SECRET``` and ```REFRESH_TOKEN_SECRET``` in Workflow [Fixes #485]

src/directives/authDirective.ts, src/directives/roleDirective.ts, src/libraries/errors/applicationError.ts, src/libraries/errors/conflictError.ts, src/libraries/errors/inputValidationError.ts, src/libraries/errors/internalServerError.ts, src/libraries/errors/invalidFileTypeError.ts, src/libraries/errors/notFoundError.ts, src/libraries/errors/unauthenticatedError.ts, src/libraries/errors/unauthorizedError.ts, src/libraries/errors/validationError.ts, src/middleware/isAuth.ts
TSDoc comments migration in the folders `src/directives, libraries, middleware.`
Yes
Yes
=> TSDoc Comments migration

src/models/Comment.ts, src/models/DirectChat.ts, src/models/DirectChatMessage.ts, src/models/Donation.ts, src/models/EncodedImage.ts, src/models/Event.ts, src/models/EventProject.ts, src/models/File.ts, src/models/Group.ts, src/models/GroupChat.ts, src/models/GroupChatMessage.ts, src/models/ImageHash.ts, src/models/Language.ts, src/models/MembershipRequest.ts, src/models/Message.ts, src/models/MessageChat.ts, src/models/Organization.ts, src/models/Plugin.ts, src/models/PluginField.ts, src/models/Post.ts, src/models/Task.ts, src/models/User.ts
TSDoc comments migration in the folder: `src/models`
Yes
Yes
=> [doc:models] TSDoc comments migration

src/resolvers/Mutation/index.ts, src/resolvers/Mutation/updateUserPassword.ts, src/resolvers/Mutation/updateUserProfile.ts, src/typeDefs/inputs.ts, src/typeDefs/mutations.ts, src/types/generatedGraphQLTypes.ts, tests/resolvers/Mutation/updateUserPassword.spec.ts, tests/resolvers/Mutation/updateUserProfile.spec.ts
This PR adds a Update Password mutation for frontend update password page to work
Fixes #1164 
Yes
Not Relevant
Not Required
No
No
Yes
=> Add password update mutation [Fixes #1164]

INSTALLATION.md
Docs change
Fixes #1167
**Summary**
the docs was misleading so I raised this PR to solve the issue
no
no
yes
=> Fixes #1167 Wrong steps in Installation.md

.env.sample
Refractored Environment variables.
Fixes  #1012 
Not required.
Not required.
Not required.
**Summary**
Changed the firebase `env` to make  them completely invalid but keeping their format consistent.
Yes
=> Better configuration support for Firebase on installation closes #1012

.env.template, .pylintrc, installer.py, requirements.txt
This PR is a feature addition. I have added a python script in the root directory of the project which will help in a much quicker and efficient way of setting up talawa-api for developers.
1. If no `.env` file exists in the root directory : -
https://user-images.githubusercontent.com/92572013/224138342-87e404d4-5f35-428b-92e2-eaaa9d643cae.mp4
<br>
2. If `.env` file exists with some values already assigned : -
https://user-images.githubusercontent.com/92572013/224139507-9c9d4825-49ec-4f18-b78a-5b890d25d468.mp4
<br>
The motivation to raise this feature request and work on it was convenience and saving time of developers who wish to contribute to talawa. Many people make minor errors in a hassle to setup a project and that leads them to unnecessary errors and eventually loosing motivation …
=> [feature request] : Python script to automate installation process

src/typeDefs/inputs.ts
bugfix
Fixes #1180
No
-
-
**Summary**
Explained in #1180
No
-
Yes
=> fix: Fixed incorrect type for UpdateUserTagInput in graphql schema

.env.sample, INSTALLATION.md, src/constants.ts, src/utilities/mailer.ts
It adds the custom smtp server mailer support to talawa applications suite.
Fixes PalisadoesFoundation/talawa-admin#457
Not Required
Yes
No
No
Yes
=> SMTP Transporter Configuration for Mailer [Fixes #457 in Talawa Admin]  

src/utilities/auth.ts
Bug/feature fix
Fixes #1188 
No I did not
No I did not.
**Summary**
The admin portal timeout was 15 minutes which was not enough time to make changes on the portal. I have now changed the timeout to 40 minutes which is fair enough and gives users enough time to make relevant changes on the portal.
No
=> Bug Report: TImeout for User is short #1188

src/constants.ts, src/resolvers/Mutation/createUserTag.ts, src/resolvers/Mutation/index.ts, tests/helpers/tags.ts, tests/resolvers/Mutation/createUserTag.spec.ts
Feature
Fixes part of #1126 
Yes
NA
NA
**Summary**
Adds the source code and tests for `createUserTag` mutation.
No
Yes
=> Add `createUserTag` mutation [Fixes part of #1126]

tests/resolvers/Query/eventsByOrganizationConnection.spec.ts
This Pull Request includes tests written for file `src/resolvers/Query/eventsByOrganizationConnection.ts`. The test cases are covered for for all the functionalities and cases in the file
**Issue Number:** #1159 
This PR closes #1159
**Did you add tests for your changes?  Yes** 
The code coverage obtained is 100%.
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?** Yes
=> tests for file `src/resolvers/Query/eventsByOrganizationConnection.ts`

src/resolvers/Mutation/index.ts, src/resolvers/Mutation/removeUserTag.ts, tests/resolvers/Mutation/removeUserTag.spec.ts
Feature
Fixes part of #1126 
Yes
NA
NA
**Summary**
Added the `removeUserTag` mutation for the `UserTag` type introduced earlier. 
No
NA
Yes
=> Add resolver for `removeUserTag` mutation [Fixes part of #1126]

INSTALLATION.md
Correct errors in INSTALLATION.md
Fixes #1228 
No
No
**Summary**
No
Yes
=> correct errors in INSTALLATION.md

CONTRIBUTING.md, src/server.ts
Bugfix
Fixes #1243 
NA
NA
NA
**Summary**
Currently the `/voyager` endpoint is only exposed when the `NODE_ENV` is set to `development`. This is not ideal, as even when running the command `npm run dev`, by default the `NODE_ENV` is set to `undefined`, and thus the users can't access the same. A better check would be to not expose the same in the `production` environment, and expose it in all other environments.
Also corrected the relative path for the image to be displayed in the documentation for Voyager. 
No
NA …
=> Bug fix for added Voyager Endpoint [Fixes #1243]

src/resolvers/Mutation/updateUserType.ts, tests/resolvers/Mutation/updateUserType.spec.ts
This PR increases the code coverage for ```updateUserType.ts``` file from 90% to 100%
Fixes #1253 
Yes
NR
**Summary**
This PR increases the code coverage for ```updateUserType.ts``` file from 90% to 100%
No
Yes
=> Increase Code Coverage for updateUserType.ts [Fixes #1253]

.github/workflows/pull-request.yml, src/typeDefs/inputs.ts, src/typeDefs/mutations.ts, src/types/generatedGraphQLTypes.ts
Bugfix
Fixes #1254 
NA
NA
NA
**Summary**
Removed the unused mutation and its input type definitions. Also as a small fix, corrected the spelling of `typpe` in the workflow file.
No
NA
Yes
=> Remove `createGroup` mutation [Fixes #1254]

tests/resolvers/Mutation/addOrganizationImage.spec.ts, tests/resolvers/Mutation/addUserImage.spec.ts, tests/resolvers/Mutation/createEventProject.spec.ts, tests/resolvers/Mutation/otp.spec.ts, tests/resolvers/Mutation/removeEventProject.spec.ts, tests/resolvers/Mutation/removePost.spec.ts
Refactoring Tests
Fixes #1267 
Not Required
NA
Not Relevant
**Summary**
- In many test files, there was unnecessary mocking of constants
- Removed redundant mocks 
No
Discussion - https://github.com/PalisadoesFoundation/talawa-api/pull/1262#pullrequestreview-1376198678
Yes
=> Removed Redundant mocks for constants

src/resolvers/Mutation/rejectMembershipRequest.ts, tests/resolvers/Mutation/rejectMembershipRequest.spec.ts
Refactoring
Fixes #1278 
No
Not required
Not relevant
No
Not required
Yes
=> code refactored for rejectMembershipRequest.ts

src/resolvers/Mutation/leaveOrganization.ts
Refactoring
Fixes #1280 
No
Not required
Not relevant
No
Not required
Yes
=> $pull implemented for leaveOrganization.ts

.github/workflows/push-documentation.yml, .github/workflows/push.yml, package-lock.json
Bugfix
Migrated the `checkout` action to use the `TALAWA_DOCS_SYNC` token. If the token has been provided with all the necessary privileges, now the action should pass and update the docs repository successfully. 
Fixes #1240 
NA
NA
NA
**Summary**
NA
No
NA
Yes
=> Fix for Push Workflow

.github/workflows/push-documentation.yml
=> Move the directory for autogenerated docs in GitHub Actions

src/resolvers/Mutation/adminRemoveEvent.ts, tests/resolvers/Mutation/adminRemoveEvent.spec.ts
Refactoring
Fixes #1312
No
Not required
Not relevant
No
Not required
Yes
=> $pull and select() implemented

src/directives/authDirective.ts, src/libraries/requestContext.ts, src/resolvers/Organization/image.ts, src/resolvers/Subscription/messageSentToDirectChat.ts, src/resolvers/Subscription/messageSentToGroupChat.ts, src/utilities/auth.ts, tests/directives/authDirective.spec.ts, tests/directives/roleDirective.spec.ts, tests/libraries/errors/internalServerError.spec.ts, tests/libraries/errors/unauthenticatedError.spec.ts, tests/libraries/requestContext.spec.ts, tests/middleware/isAuth.spec.ts, tests/resolvers/Mutation/addOrganizationImage.spec.ts, tests/resolvers/Mutation/addUserToGroupChat.spec.ts, tests/resolvers/Mutation/blockPluginCreationBySuperadmin.spec.ts, tests/resolvers/Mutation/createEventProject.spec.ts, tests/resolvers/Mutation/createOrganization.spec.ts, tests/resolvers/Mutation/login.spec.ts, tests/resolvers/Mutation/removeEventProject.spec.ts, tests/utilities/graphqlConnectionFactory.spec.ts, tests/utilities/reuploadDuplicateCheck.spec.ts, tests/utilities/superAdminCheck.spec.ts, tests/utilities/uploadImage.spec.ts
Fix
Fixes #1322 
No
Not required
Not relevant
No
Not required
Yes
=> removed unnecessary async/await syntax

src/models/index.ts
Fix
Fixes #1325 
No
Not required
Not relevant
No
Not required
Yes
=> removed duplicate export

package-lock.json, package.json, src/index.ts, src/resolvers/Subscription/onPluginUpdate.ts
Fixes # (Workflo Fix) related to #1354 and #1358
N/A
The server runs successfully 
N/A
**Summary**
Just removed the native windows packages.
No
=> Fix: Removed Windows Specific Pacakges

src/resolvers/Task/creator.ts, src/resolvers/Task/event.ts, src/resolvers/Task/index.ts, tests/resolvers/Task/creator.spec.ts, tests/resolvers/Task/event.spec.ts
Bugfix
NA
Yes
NA
NA
**Summary**
As @beingnoble03 pointed out, the field level resolver for the Event and Creator fields were missing on the Task model. This PR introduces the same with 100% test coverage. 
No
NA
Yes
=> Add field level resolvers for the task modal

INSTALLATION.md
=> Fixed error in INSTALLATION.md

src/services/CommentCache/findCommentsByPostIdInCache.ts, src/services/CommentCache/findCommentsInCache.ts, src/services/EventCache/findEventInCache.ts, src/services/OrganizationCache/findOrganizationsInCache.ts, src/services/PostCache/findPostsInCache.ts
Bug fix
Fixes #1408 
**Summary**
Yes
=> Null Pointer error fixed

.eslintrc.json, tests/helpers/posts.ts, tests/helpers/task.ts, tests/resolvers/UserTag/usersAssignedTo.spec.ts, tests/utilities/adminCheck.spec.ts, tests/utilities/deleteImage.spec.ts, tests/utilities/encodedVideoStorage/uploadEncodedVideo.spec.ts, tests/utilities/imageExtensionCheck.spec.ts, tests/utilities/reuploadDuplicateCheck.spec.ts, tests/utilities/superAdminCheck.spec.ts
This pull request is related to typescript lint warnings. I have resolved around 15 warnings and made changes to 9 files.
#1201 
Fixes #1201 
No
N/A
No
**Summary**
I have updated some of the typescript lint warnings that came up when running npm run lint:check.
Some of the warnings that I have resolved were:
1. Removing the "specify a different type" error after going through the codebase.
2. Adding proper null-check in various cases where null-checks were missing and resulted in a warning.
No
N/A …
=> Fixing Typescript Rules lint warnings

INSTALLATION.md, setup.ts
- Implemented the setup of Recaptcha Site Key for setting up the .env file by using `npm run setup` command.
- Added docs for Recaptcha site key in `INSTALLATION.md` file.
Fixes #1444 
No
https://github.com/PalisadoesFoundation/talawa-api/assets/116940083/45b70876-794c-4909-a9dd-bf834448e1a7
You can observe in screen recording that only `RECAPTCHA_SECRET_KEY` is added to `.env` file.
https://github.com/PalisadoesFoundation/talawa-api/assets/116940083/3d8df112-c6de-436a-a417-eb3eef0e13dc
**Summary**
No …
=> fix: implemented reCaptcha Site key setup and added docs

.github/workflows/pull-request.yml
Fixes #1433 
Not required
**Summary**
Now linting formating and type checking will only run for modified files.
No
=> Fix linting, formatting and type checking in modified files only.

.env.sample, INSTALLATION.md, setup.ts
The PR introduces an option in the setup interface regarding the settting of NODE_ENV variable and some changes in INSTALLATION.md
Fixes #1443 
No
demonstrates the changes in setup.ts file -->
[Screencast from 04-12-23 10:28:46 PM IST.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/132701661/2fafdf75-b9b2-4ae0-9ea8-d4a5b70bc99c)
documentation change -->
Established a distinct section for configuring the .env file, previously located within the Docker Installation section.
**Summary**
The pull request streamlines the project setup in a local environment, improves clarity in configuring the .env …
=> [#1443]Made setup interface for NODE_ENV variable and some changes in INSTALLATION.md

package-lock.json, package.json, src/resolvers/Mutation/forgotPassword.ts
refactoring
Fixes #1462 
No
**Summary**
Upgraded jwt-decode package from 3.1.2 to 4.0.0
No
Yes
=> #1462 upgraded jwt-decode to 4.0.0

package-lock.json, package.json
Fixes #1463
N/A
N/A
N/A
**Summary**
This PR updates the `express-rate-limit` package from version 5.5.1 to 7.1.5 to address security concerns.
No
N/A
Yes
=> Feat: Upgrade package express-rate-limit from 5.5.1 to 7.1.5 #1463

schema.graphql, src/typeDefs/enums.ts, src/types/generatedGraphQLTypes.ts
This PR makes sure that sorting of the organizations is done correctly based on the creation date. 
Fixes #1497 
No
Not relevant
**Summary**
- Added `createdAt_ASC` and `createdAt_DESC` to the OrganizationOrderByInput enum in schema.graphql.
- Ensured consistency by updating the enums.ts file to reflect the new sorting options.
- Validated and confirmed the accurate generation of GraphQL types in genratedGraphQlTypes.ts.
No
Users can now utilize the new sorting options in the ORGANIZATION_CONNECTION_LIST GraphQL query to efficiently retrieve …
=> feat(graphql):  Added createdAt respective attributes to OrganizationOrderByInput

package-lock.json, package.json
- Upgraded graphql-voyager from 1.0.1 to 2.0.0
Fixes #1461 
No
**Summary**
- Ensured the proper working of api even after upgradation of graphql-voyager dependency
No
Yes
=> chore(deps): upgrade graphql-voyager

setup.ts
Earlier the setup script wasn't asking for `LAST_RESORT_SUPER_ADMIN` but now it will.
Fixes #1524 
Yes
Not required
**Summary**
No
Yes
=> setup script will now ask for super admin email

INSTALLATION.md
Added typescript installation
Fixes #1529 
NA
**Summary**
Yes
=> added typescript installation guide

.husky/pre-commit, CODE_OF_CONDUCT.md, CONTRIBUTING.md, DOCUMENTATION.md, INSTALLATION.md, ISSUE_GUIDELINES.md, PR_GUIDELINES.md, README.md, package-lock.json, package.json, scripts/githooks/update-toc.js
script to generate table of contents for markdown files.
Fixes #
**Summary**
=> table of content script

package-lock.json, package.json, src/app.ts
Upgrade the express-rate-limit package from 5.5.1 to 7.1.5
Fixes #1463 
NA
**Summary**
Yes
=> updated express-rate-limit package

src/resolvers/Mutation/createEvent.ts, tests/resolvers/Mutation/createEvent.spec.ts
Reverts PalisadoesFoundation/talawa-api#1602
We have reviewer requests that were not applied
=> Revert "Create weekly event recurring instance"

.github/workflows/check_files_submitted.py, .github/workflows/pull-request.yml
This PR introduces a feature. The feature ensures that every time a new PR is submitted. The number of files submitted
is less than 20. If it exceeds 20, the Github Action Fails.
Fixes #1556
No
No
**Summary**
Yes
=> Added Github Action to check number of files submitted during PR.

.eslintrc.json, .husky/pre-commit, package-lock.json, package.json
Reverts PalisadoesFoundation/talawa-api#1635
It's causing other PRs to fail. This needs to be fixed without impacting others
=> Revert "Lint only updated files with stricter linting"

package-lock.json, setup.ts
Feature
Fixes #1606 
No
https://github.com/PalisadoesFoundation/talawa-api/assets/116940083/37fb6a7d-c475-4006-bcc0-f8690696158e
- Case 1: User configures SMTP with correct credentials
https://github.com/PalisadoesFoundation/talawa-api/assets/116940083/d031ff82-d873-4073-8a35-22bdaa2b5eb3
- Case 2: Users skips to configure SMTP
**Summary**
Added script to configure SMTP environment variables during setup
No
Yes
=> fix: updated setup.ts script to configure and verify SMTP credentials in env file during setup

package-lock.json, package.json, src/types/generatedGraphQLTypes.ts
Upgraded the `@graphql-codegen/typescript` and `@graphql-codegen/typescript-resolvers` to 4.0.1, the issue was just to update `graphql-codegen/typescript-resolvers` package but as a need to update this package I have to upgrade the `@graphql-codegen/typescript`package too.
Fixes #1511 
**Summary**
=> package updated

setup.ts, src/types/generatedGraphQLTypes.ts
It  improve MongoDB configuration during setup mentioned in #1605
Fixes #1605 
No
N/A
N/A
**Summary**
Implemented all requirement asked in open issue - https://github.com/PalisadoesFoundation/talawa-api/issues/1605
Also fixed same for redis url auto population during docker installation. 
No
N/A
Yes
=> Auto Detect MongoDB URL during setup, Fixes #1605

src/constants.ts, src/env.ts, src/utilities/mailer.ts
It fixes the API Startup Error Messages.
Fixes #1521 
No
**Summary**
When non docker API instance is started, it displayed some error messages related to the .env variables.This PR fixes those problems by redefining the structure of schema.
No
Yes
=> fixed the structure of env.ts, redefined .env schema  and made some type changes

schema.graphql
This PR makes schema.graphql up to date with the codebase
Fixes #1775 
No
No
=> fix: update schema.graphql to reflect latest changes in the codebase

src/libraries/logger.ts
BugFix
Fixes #1549 
**Summary**
=> Console logging shows {} values where variables or nothing should appear#1549

.github/workflows/md_to_mpx.py, .github/workflows/push.yml, README.md, schema.graphql
bugfix
Fixes #1559 
No
No
**Summary**
Tested the working of push workflow and integrated a script which make .md files mpx compatible.
No
Yes
=> Tested the push workflow and made the md files mpx compatible

package-lock.json, package.json
Removed the ts-node dependency
=> Removed the ts-node dependency

.github/workflows/pull-request.yml
Bugfix
Fixes #1548
**Summary**
=> fix: workflow linting fix

package-lock.json, package.json
Reverts PalisadoesFoundation/talawa-api#1794
=> Revert "chore(deps): bump prettier from 2.8.8 to 3.2.5"

src/resolvers/Mutation/updateUserProfile.ts, tests/resolvers/Mutation/updateUserProfile.spec.ts
Added tests for src/resolvers/Mutation/updateUserProfile.ts.
Fixes #1822 
N/A
All the tests after adding the test
Overall code coverage for the file
N/A
**Summary**
Increasing code coverage of the file to 100%
No
=> Added tests for the file src/resolvers/Mutation/updateUserProfile.ts

package-lock.json, src/resolvers/Mutation/forgotPassword.ts, tests/resolvers/Mutation/forgotPassword.spec.ts
Reverts PalisadoesFoundation/talawa-api#1852
=> Revert "Potential Privilege Escalation BugFix"

.github/workflows/ci.yml.archive, .github/workflows/codeql-codescan.yml, .github/workflows/pull-request.yml, .github/workflows/pull_changes.yml, .github/workflows/push-documentation.yml, .github/workflows/push.yml
Updated github actions to the latest versions
=> Updated github actions to the latest versions

tests/resolvers/middleware/currentUserExists.spec.ts
This PR fixes tests for src/resolvers/middleware/currentUserExists.ts., increasing the line coverage.
Fixes #1818
NA
NA
NA
**Summary**
This PR changes the way the file was being tested, to increase its line coverage.
No
NA
Yes
=> Fixed Tests for src/resolvers/middleware/currentUserExists.ts

schema.graphql, src/resolvers/Organization/index.ts, src/typeDefs/types.ts, src/types/generatedGraphQLTypes.ts, tests/resolvers/Organization/posts.spec.ts
Reverts PalisadoesFoundation/talawa-api#1910
=> Revert "Fix/fetch postby user"

schema.graphql, src/resolvers/Organization/index.ts, src/typeDefs/types.ts, src/types/generatedGraphQLTypes.ts, tests/resolvers/Organization/posts.spec.ts
Reverts PalisadoesFoundation/talawa-api#1913
=> Revert "Revert "Fix/fetch postby user""

.env.sample
minor change made to stop github action , for mongoose branch 
fixes: #1695
=> minor changes for Mongoose 8.2.0

schema.graphql, src/resolvers/Mutation/updateUserProfile.ts, src/typeDefs/inputs.ts, src/types/generatedGraphQLTypes.ts
feature
Fixes #1998 
No
**Summary**
This PR implements the logic for updation of default language of the user in the updateUserProfile mutation. 
No
Yes
=> Fixes the updateUserProfile mutation

.github/workflows/pull-request.yml, .github/workflows/push-documentation.yml, .github/workflows/push.yml
Fixes #2030
- N/A
- N/A
- N/A
**Summary**
- N/A
- No
- N/A
Yes
=> Updated sleep-action to v2

package-lock.json, package.json, src/resolvers/Mutation/addUserCustomData.ts, src/resolvers/Mutation/login.ts, src/resolvers/Query/customFieldsByOrganization.ts
Upgrade of typescript to 5.4.2 from 5.3.2.
Fixes #2026 
No
No
**Summary**
Typescript upgraded and changes made in files where required.
No
Yes
=> Typescript upgraded to 5.4.2

tests/resolvers/Query/post.spec.ts
Improved the code coverage to 100%
Fixes #1927
**Summary**
Yes
=> Test src/resolvers/query/post.ts

schema.graphql, src/models/Fund.ts, src/resolvers/Fund/creator.ts, src/resolvers/Fund/index.ts, src/resolvers/Mutation/createFund.ts, src/resolvers/Mutation/removeFund.ts, src/resolvers/Query/fundsByOrganization.ts, src/resolvers/Query/helperFunctions/getWhere.ts, src/typeDefs/inputs.ts, src/typeDefs/queries.ts, src/typeDefs/types.ts, src/types/generatedGraphQLTypes.ts, tests/helpers/Fund.ts, tests/resolvers/Fund/creator.spec.ts, tests/resolvers/Mutation/createFund.spec.ts, tests/resolvers/Mutation/removeOrganization.spec.ts, tests/resolvers/Mutation/updateFund.spec.ts, tests/resolvers/Query/fundsByOrganization.spec.ts
This PR adds support for Funds screen according to the latest design. It is related to this [PR](https://github.com/PalisadoesFoundation/talawa-admin/pull/1790) of Talawa-Admin
Fixes #2085 
Yes 
N/A
No
**Summary**
- Added CreatorId in the funds schema.
- Ensured createFund mutation has creatorId.
- Corrected the logic of authorization for removefunds mutation.
- Added a new query to fetch all the funds by organizationId, so that it also helps for filtering by name.
- Covered code by tests.
- Updated the fundupdate mutation to handle the updation of referenceId.
- Ensured all relevant types are updated according …
=> feat: Added Support for the Funds Screen

src/setup/MongoDB.ts, src/utilities/loadSampleData.ts
The MongoDB connection error was resolved after removing 'userTypeFix' and adding verification for all collections after importing sample data.
Fixes #2049 
No
No
**Summary**
Verification is performed by comparing the documents in the json file of sample_data to the documents in the collection in MongoDB after import.
No
Similar issue: #2099 
=> MongoDB Connection error solved after removing `userTypeFix`

tests/utilities/checkReplicaSet.spec.ts
This PR introduces tests for the missing lines present in `checkReplicaSet.ts` file. 
Fixes #2082 
Yes
N/A
**Summary**
- Made sure `checkReplicaSet.ts` file has 100% code coverage.
No
Yes
=> test: Added tests for checkReplicaSet.ts

tests/resolvers/Mutation/removeSampleOrganization.spec.ts
This PR makes sure `removeSampleOrganization.ts` has 100% code coverage.
Fixes #2079 
Yes
N/A
**Summary**
- Removed the test which is skipped
- Added test to ensure admins can removeSampleOrganization without an error.
- Ensured 100% code coverage.
- Removed a redundant test case.
No
Yes
=> Tests: Added tests for `removeSampleOrganization.ts`

tests/resolvers/Mutation/updateActionItemCategory.spec.ts
This PR ensures the `updateActionItemCategories.ts` file has 100% code coverage.
Fixes #2076 
Yes
N/A
**Summary**
- Added tests for the uncovered lines
- Ensured code coverage for this file is 100%
No
Yes
=> tests: Added tests for `updateActionItemCategories.ts`

tests/resolvers/Mutation/createAgendaItem.spec.ts
This PR adds tests for the uncovered lines of `createAgendaItem.ts file`.
Fixes #2073 
Yes
N/A
**Summary**
- Ensures 100% codecoverage for `createAgendaItem.ts` file.
No
Yes
=> tests: Modified tests of `createAgendaItem.ts`

src/env.ts
fixed the  MongoDB, not connecting error
Fixes #2119
N/A
**Snapshots:**
**Summary**
fixed  MongoDB not connecting error by making sure that mongoose.connect() should be able to read the mongo uri from .env file.
but this introduces a new error of duplicate ids because of the wrong workflow in the loadSampleData.js, which needs to be resolved  in a separate issue .
NO
Yes
=> Fix: loadSampleData isn't working

tests/resolvers/Mutation/updateUserRoleInOrganization.spec.ts
Improve the code coverage of the file to 100%
Fixes #2065
YES
**Summary**
=> Test src/updateUserRoleInOrganization.ts

tests/resolvers/Mutation/deleteVenue.spec.ts
Tests for `deleteVenue.ts` file.
Fixes #2072 
Yes
N/A
**Summary**
- Achieved 100% test coverage for `deleteVenue.ts` file.
No
Yes
=> tests: Added tests for `deleteVenue.ts`

src/resolvers/Query/index.ts
`getEventAttendeesByEventId,`
`getEventAttendee` these resolvers  included in Query
Fixes #2128
**Summary**
=>  Bug Report: Query is not included in Resolvers (PR) 

tests/resolvers/Mutation/createVenue.spec.ts
Tests for `createVenue.ts` file.
Fixes #2069 
Yes
N/A
**Summary**
- Ensured 100% code coverage for `createVenue.ts` file.
No
Yes
=> tests: Added tests for `createVenue.ts`

tests/resolvers/Mutation/editVenue.spec.ts
Tests for `editvenue.ts` file.
Fixes #2067 
Yes
N/A
**Summary**
- Added tests to ensure 100% code coverage for `editVenue.ts` file.
No
Yes
=> tests: added tests for `editVenue.ts`

tests/resolvers/Mutation/updateUserProfile.spec.ts
100% code coverage for this `updateUserProfile.ts` file.
Fixes #2070 
Yes
N/A
**Summary**
- Modified the `updateUserProfile` tests file to ensure 100% code coverage.
No
Yes
=> tests: modified the `updateUserProfile`

schema.graphql, src/typeDefs/inputs.ts, src/typeDefs/mutations.ts, src/types/generatedGraphQLTypes.ts
BugFix
Fixes #2139 
Not needed
**Summary**
Removed the updateUserType mutation as it is not needed anymore.
No
=> removed updateUserType mutation

tests/resolvers/Mutation/updateAgendaSection.spec.ts
Tests for `updateAgendaSection.ts` file to ensure 100% code coverage.
Fixes #2068 
Yes
N/A
**Summary**
- Added tests for `updateAgendaSection.ts` file to ensure 100% code coverage.
No
Yes
=> tests: Added test for `updateAgendaSection.ts`

src/resolvers/Mutation/updateFundraisingCampaign.ts, tests/resolvers/Mutation/updateFundraisingCampaign.spec.ts
Fixes `updataFundraisingCampaign.ts` and its tests.
Fixes: #2059 
Yes
=> fix: tests for `updateFundraisingCampaign`

src/checks.ts
Minor bug
Fixes #2228
NA
NA
**Summary**
NA
No
NA
yes
=> Fix userType for `LAST_RESORT_SUPERADMIN_EMAIL`

src/utilities/TalawaGraphQLError.ts
feature
Fixes #2223
No
-
Not yet, will find the time to do so soon
**Summary**
Added the `TalawaGraphQLError` class as discussed in the linked issue. The class is highly documented to ensure that the contributers can easily grasp the usage patterns. 
No
-
Yes
=> added TalawaGraphQLError class

src/helpers/event/recurringEventHelpers/generateRecurringEventInstances.ts, src/models/Event.ts, src/resolvers/Query/event.ts, src/resolvers/Query/eventsByOrganization.ts, src/resolvers/Query/eventsByOrganizationConnection.ts, src/resolvers/Query/registeredEventsByUser.ts, src/typeDefs/types.ts, src/types/generatedGraphQLTypes.ts, src/utilities/createSampleOrganizationUtil.ts, tests/resolvers/Query/event.spec.ts, tests/resolvers/Query/eventsByOrganization.spec.ts, tests/resolvers/Query/eventsByOrganizationConnection.spec.ts, tests/resolvers/Query/registeredEventsByUser.spec.ts, tests/utilities/createSampleOrganizationUtil.spec.ts
Removes event `status` and its usage.
Fixes #2241 
Not required.
=> Remove Event's `status` field

.github/workflows/pull-request.yml
Ensure the videos directory is present before executing tests to prevent failures due to its absence.
Fixes #2235 
https://github.com/PalisadoesFoundation/talawa-api/assets/112749383/14140232-85ff-4e06-904f-cf4e18d660ab
https://github.com/PalisadoesFoundation/talawa-api/assets/112749383/9096c081-13cf-44cf-af69-5bd265e955f8
https://github.com/PalisadoesFoundation/talawa-api/assets/112749383/3b86014e-69d5-4151-8141-8abbe6795640
N/A
**Summary**
To address this issue, we can add a step to create a `videos/` directory in the `pull-request.yml` file within the `Test-Application workflow` check. This adjustment would ensure that the test does not fail due to …
=> Fix: Ensure videos directory is created before running tests

INSTALLATION.md
Updates INSTALLATION.md to be clearer on Docker installation
Fixes #2268
- N/A
- N/A
- N/A
**Summary**
- See above
- No
- N/A
Yes
=> Updated the installation steps. Fixes #2268

INSTALLATION.md
Updates INSTALLATION.md to be clearer on Docker installation
Fixes #2268
- N/A
- N/A
- N/A
**Summary**
- See above
- No
- N/A
Yes
=> Fixes #2268 v3

INSTALLATION.md
Updates INSTALLATION.md to be clearer on Docker installation
Fixes #2268
- N/A
- N/A
- N/A
**Summary**
- See above
- No
- N/A
Yes
=> Fixes #2268 - Ubuntu docker-compose Path

.dockerignore, INSTALLATION.md
Updates INSTALLATION.md to be clearer on Docker installation
Fixes #2268
- N/A
- N/A
- N/A
**Summary**
- See above
- No
- N/A
Yes
=> Fixes #2268 v4

README.md, src/resolvers/Query/index.ts
bugfix
Fixes #2293 
Yes 
**Summary**
- `getFundraisingById` resolver wasn't declared in `src/Query/resolver/index.ts` hence returning null on invoking from admin
No
Yes
=> Fix error invoking getFundraisingById Resolver

README.md, src/resolvers/FundraisingCampagin/campaignPledges.ts, tests/resolvers/FundraisingCampaign/pledge.spec.ts
bugfix
Fixes #2296 
Yes 
**Summary**
- Error was caused as campaignId was used to find pledges which should be campaigns.
- Added code to populate users involved in pledge
No
Yes
=> Fixed error in populating pledges & its users

INSTALLATION.md
Reverts PalisadoesFoundation/talawa-api#2798
=> Revert "Updated documentation to include production setup"

INSTALLATION.md
Reverts PalisadoesFoundation/talawa-api#2801
=> Revert "Revert "Updated documentation to include production setup""

.github/workflows/push-deploy-website.yml
=> Fixed Deploy v1

.github/workflows/push-deploy-website.yml
=> Testing the workflow for deployment

.github/workflows/push.yml
Reverts PalisadoesFoundation/talawa-api#2900
This had to be reverted. It's causing major errors with linting
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/12965541120/job/36165387631
=> Revert "Update push.yml"

.github/workflows/push.yml
Reverts PalisadoesFoundation/talawa-api#2904
This is not the cause
=> Revert "Revert "Update push.yml""

.github/workflows/push.yml
Reverts PalisadoesFoundation/talawa-api#2905
=> Revert "Revert "Revert "Update push.yml"""

package.json, pnpm-lock.yaml
Reverts PalisadoesFoundation/talawa-api#3116
=> Revert "chore(deps): bump drizzle-seed from 0.3.0 to 0.3.1"

package.json, pnpm-lock.yaml
Reverts PalisadoesFoundation/talawa-api#3115
=> Revert "chore(deps): bump drizzle-kit from 0.30.2 to 0.30.4"

package.json, pnpm-lock.yaml
Reverts PalisadoesFoundation/talawa-api#3114
=> Revert "chore(deps): bump drizzle-orm from 0.38.4 to 0.39.1"

package.json, pnpm-lock.yaml
Reverts PalisadoesFoundation/talawa-api#3113
=> Revert "chore(deps): bump minio from 8.0.3 to 8.0.4"

package.json, pnpm-lock.yaml
Reverts PalisadoesFoundation/talawa-api#3112
=> Revert "chore(deps): bump @sinclair/typebox from 0.34.14 to 0.34.15"

.devcontainer/devcontainer.json
Reverts PalisadoesFoundation/talawa-api#3119
=> Revert "initializeCommand modified"

.devcontainer/devcontainer.json
Reverts PalisadoesFoundation/talawa-api#3127
=> Revert "Revert "initializeCommand modified""

package.json, pnpm-lock.yaml
Reverts PalisadoesFoundation/talawa-api#3126
=> Revert "Revert "chore(deps): bump @sinclair/typebox from 0.34.14 to 0.34.15""

package.json, pnpm-lock.yaml
Reverts PalisadoesFoundation/talawa-api#3125
=> Revert "Revert "chore(deps): bump minio from 8.0.3 to 8.0.4""

package.json, pnpm-lock.yaml
Reverts PalisadoesFoundation/talawa-api#3124
=> Revert "Revert "chore(deps): bump drizzle-orm from 0.38.4 to 0.39.1""

package.json, pnpm-lock.yaml
Reverts PalisadoesFoundation/talawa-api#3123
=> Revert "Revert "chore(deps): bump drizzle-kit from 0.30.2 to 0.30.4""

package.json, pnpm-lock.yaml
Reverts PalisadoesFoundation/talawa-api#3122
=> Revert "Revert "chore(deps): bump drizzle-seed from 0.3.0 to 0.3.1""

.devcontainer/devcontainer.json, docker/api.Containerfile, package.json
Reverts PalisadoesFoundation/talawa-api#3148
1. We still have the issue
2. You were not assigned the issue either
=> Revert "pnpm roll back"

.devcontainer/devcontainer.json, docker/api.Containerfile, package.json
Reverts PalisadoesFoundation/talawa-api#3150
=> Revert "Revert "pnpm roll back""

envFiles/.env.deploy
- Added .env.deploy for test.talawa.io
- N/A
- N/A
- N/A
- N/A
- Yes
=> Added .env.deploy for test.talawa.io

docs/docs/docs/developer-resources/rate-limiting.md, docs/docs/docs/developer-resources/testing.md
=> docs: Add documentation for rate limiting in GraphQL API
