constants.js, helper_functions/imageExtensionCheck.js, helper_functions/uploadImage.js
Refactoring image upload and extension check util.
No.
Not required.
**Summary**
The image upload and image extension check function has been refactored to avoid redundant file operations in case of invalid extension, Its just that now we are avoiding writing to the disk if we have invalid file extension instead of first writing and then deleting the file.
Also, I've removed delete function call from extension validator as it should not be responsible for deleting the files.
No. Essentially the end result will be the same.
=> removing redundant file operations in case of invalid extension

resolvers/functions/creatorCheck.js
-bugfix 
**Summary**
-There was bug while comparing, string and int cannot be === as there needs to be the same datatype but when we use == the datatypes are ignored rather the content is compared.
issue no. #223
=> bug issue#223 resolved

resolvers/event_mutations/createEvent.js
BugFix
Fixes #276 
No
The above image shows a user who isn't a part of org trying to create an event in org and received an error 
No
**Summary**
Previously a user was able to create an event in an org even if they aren't a member of the org, This PR tends to resolve this issue.
Here `flag` is a variable that is used to handle condition. if `flag = 0` that means the user isn't a part of org and the API returns an error. If `flag = 1` this means that the user is a part of the org and we proceed with further steps.
```  
JoinedOrg.forEach((orgID) => {
if (orgID.equals(args.data.organizationId)) {
flag = 1;
}
}); …
```
=> Fixed Create Event Mutation: Fixes #276

tests/functions/getToken.js, tests/user.spec.js
testing
Fixes #362 , #363 
Yes
No
**Summary**
- To precisely test the signup, login mutation, and all users Query.
- To Fix issue #362 
- To Fix issue  #363
-  `tests/functions/getToken.js` was modified because whenever a test runs it checks for `token` using `beforeAll` in jest. But when tests run without the user existing, it doesn't return the token. Because of this, many tests are getting failed. To deal with this, I have added `SignUp` to it and it returns the token for the first time. Later, since the user exists, all the tests which require token run correctly.
- This is a high-priority issue for dealing …
=> Test: Revamped All Users Query, SignUp and Login Mutation Tests

resolvers/block_user_mutations/block_user.js, resolvers/block_user_mutations/unblock_user.js, tests/block_user_functionality_tests.spec.js
bugfix
Fixes #439 
Yes
N/A
**Summary**
- `blockUser` mutation works correctly.
- `unblockUser` mutation works correctly.
- Tests run correctly.
- To resolve #439 
=> Fix: Block user mutation with Tests

package-lock.json
Reverts PalisadoesFoundation/talawa-api#598
=> Revert "Bump follow-redirects from 1.14.7 to 1.14.9"

lib/helper_lib/request-tracing/index.js, lib/helper_lib/request-tracing/package-lock.json, lib/helper_lib/request-tracing/package.json
Fixes a bug by upgrading `nanoid` to `3.1.31`. Updates `lib/helper_lib/request-tracing/index.js` file to use the upgraded version of  `nanoid`.
Fixes #477 
No
Not required
Not required
No
Yes
=> Upgrade nanoid to 3.1.31

.github/workflows/pull-request.yml, lib/resolvers/user_query/users.js, tests/resolvers/organization_query/organizations.spec.js, tests/resolvers/user_query/users.spec.js
bugfix
Fixes #628 
No
* Query
* Response
No
**Summary**
While logged-in to talawa-admin, the error `"message": "Cannot return null for non-nullable field Organization.name."`  is generated. But in normal circumstances, The component should be rendered properly with organization lists and with logged-in user details.
No
Yes
=> [Fixes] Error: While logged-in into talawa-admin

CONTRIBUTING.md
Repairs the broken link to Documentation to Set Up the Project in contributing.md file
Fixes #619 
Yes
=> Repaired broken link to documention for Setting Up Project in contributing.md

lib/resolvers/user_query/myLanguage.js, tests/resolvers/user_query/myLanguage.spec.js
Tests for resolvers
Fixes #546 
Yes
No
**Summary**
Added tests for `lib/resolvers/user_query/myLanguage.js`
Its covering 100% code except 1/4 branch because we can't have i18n support in testing environment following the discussion on slack channel.
No
Yes
=> [Fixes] Resolvers: Create tests for myLanguage.js 

lib/resolvers/user_query/userLanguage.js, tests/resolvers/user_query/userLanguage.spec.js
Tests for resolvers
Fixes #548 
Yes
No
**Summary**
Added tests for `lib/resolvers/user_query/userLanguage.js`
Its covering 100% code except 1/4 branch because we can't have i18n support in testing environment following the discussion on slack channel.
No
Yes
=> [Fixes] Resolvers: Create tests for userLanguage.js

lib/resolvers/post_query/commentsByPost.js
Bugfix
Fixes  #658 
No
**Summary**
In the current code, commentFound returns an empty object which results in `(!commentFound)` to be false everytime, even when there was no comment found
To fix this, I've changed `(!commentFound) to (!commentFound.length)`, when there is no comment found it will result in true and will throw an error.
Yes
=> Fix commentsByPost

lib/resolvers/functions/superAdminCheck.js, tests/functions/superAdminCheck.spec.js
Tests for resolvers
Fixes #557 
Yes
No
**Summary**
Added tests for `lib/resolvers/functions/superAdminCheck.js`.
It is covering 100% code except for 1/4 branch because of the same previous issue of not having i18n support in the testing environment.
No
Yes
=> [Fixes] Resolvers: Create tests for superAdminCheck.js

package-lock.json, package.json
Removed the package named easygraphql-tester
bugfix
Fixes #707
-
-
-
**Summary**
Removed the package named easygraphql-tester because it was not being used anywhere in the app and had a security vulnerability.
No
-
Yes
=> Removed package easygraphql-tester

tests/resolvers/group_query/groups.spec.js, tests/resolvers/plugin_query/getPlugins.spec.js
Test
Fixes #585
Yes
added required docs in code
**Summary**
Added test to improve code coverage
No
Not needed
Yes
=> Code Coverage : Tests for groups.js Fix #585

INSTALLATION.md
changes the installation guide to the correct order of commands. 
Fixes #773 
Not required
Yes
**Summary**
No
Running cp .env .env.sample makes the .env.sample file empty
Sample env contents are flushed
Content of .env.sample compiled to newliy created .env file .
change the command in that line to cp .env.sample .env
=> interchanged .env and .env.sample from the installation guide

__tests__/utilities/imageExtensionCheck.spec.ts
Adds test for `utilities/imageExtensionCheck.ts`
Fixes #799 
**Summary**
No
Yes
=> Adds test for utilities/imageExtensionCheck

__tests__/utilities/imageAlreadyInDbCheck.spec.ts
Adds tests for `utilities/imageAlreadyInDbCheck.ts`
Fixes #798 
**Summary**
No
Yes
=> Adds tests for utilities/imageAlreadyInDbCheck

__tests__/resolvers/Mutation/removeUserImage.spec.ts
Increases code coverage for `resolvers/Mutation/removeUserImage.ts` to 100%.
Fixes #561 
**Summary**
No
Yes
=> Increases code coverage for Mutation/removeUserImage

src/typeDefs/organization.ts, src/types/generatedGraphQLTypes.ts, tests/resolvers/Mutation/createOrganization.spec.ts
Allowing users to add tag while creating organization
Fixes #853 
No 
No
Yes
**Additional Context**
Made tags required, as it was a necessary field  in frontend
=> fix:tags can be added while creating organization

src/utilities/adminCheck.ts, tests/resolvers/Mutation/removeOrganizationImage.spec.ts, tests/resolvers/Mutation/updateUserProfile.spec.ts
Fixes #900 
YES
**Summary**
I also changed `adminCheck` because it had a buggy equality check for `mongoose`'s `objectId`
Added one more expect statement for `updateUserProfile` for which I wrote tests previosly.
Yes
=> Added tests for `src/lib/resolvers/Mutation/removeOrganizationImage.ts`

src/utilities/uploadImage.ts, tests/resolvers/Mutation/addUserImage.spec.ts, tests/utilities/uploadImage.spec.ts
Fixes #909 
Yes
**Summary**
Yes
=> Tests for `src/resolvers/Mutations/addUserImage`

tests/libraries/errors/internalServerError.spec.ts, tests/libraries/errors/unauthenticatedError.spec.ts
Test
Fixes #917 
**Summary**
https://github.com/PalisadoesFoundation/talawa-api/issues/917
Created a folder structure in tests folder for writing tests for files in libraries/errors. Desired tests are written in internalServerError.spec.ts
Created
Yes
=> Test: Written for internalServerError.ts file

tests/utilities/reuploadDuplicateCheck.spec.ts
Fixes #887
Yes
**Summary**
No.
Yes
=> tests for tests/utilities/reuploadDuplicateCheck.spec.ts

src/libraries/logger.ts, src/server.ts, tests/libraries/logger.spec.ts
**Issue Number:** #915 
**Did you add tests for your changes?**  : Yes
**Summary**
Mock of winston logger was created and the logger was tested for when info is sent and error is sent using spyOn. Winston createLogger, format and transports were checked to see if they are defined and called in excepted way.
There was a code block in logger.ts file which was ignored. 
A possible fix to that was to call `logger.stream` before exporting the logger. Changes have been made accordingly 
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?** : Yes
=> Tests for `src/lib/libraries/logger.ts`

tests/resolvers/Mutation/acceptAdmin.spec.ts
Increases coverage for `acceptAdmin.ts` to 100%.
Fixes #979 
Yes
NA
No
Yes
=> 100% test coverage for `acceptAdmin.ts`

src/resolvers/Query/users.ts, tests/resolvers/Query/users.spec.ts
Removes the conditional check for environment variable being equal to `PRODUCTION` for tests in `/tests/resolvers/Query`
Fixes #1005 
Yes
NA
NA
No
NA
Yes
=> Remove the conditional check `process.env !== "PRODUCTION"` for `requestContext.translate()`

src/server.ts
bugfix
Fixes #1006
-
-
-
**Summary**
Path address provided to `express.static` function is incorrect. It currently points to `/src/images` inside `src` directory which is incorrect. It should point to `/images` in the root directory. All static files should live outside the `src` directory.
-
Yes
=> fixed express static files path in server.ts

.gitignore, src/constants.ts, src/resolvers/Mutation/unregisterForEventByUser.ts, src/resolvers/Mutation/updateEvent.ts, src/resolvers/Mutation/updateEventProject.ts, src/resolvers/Mutation/updateLanguage.ts, src/resolvers/Mutation/updateOrganization.ts, src/resolvers/Mutation/updateTask.ts, src/resolvers/Mutation/updateUserProfile.ts, src/resolvers/Mutation/updateUserType.ts, tests/resolvers/Mutation/unregisterForEventByUser.spec.ts, tests/resolvers/Mutation/updateEvent.spec.ts, tests/resolvers/Mutation/updateEventProject.spec.ts, tests/resolvers/Mutation/updateLanguage.spec.ts, tests/resolvers/Mutation/updateOrganization.spec.ts, tests/resolvers/Mutation/updateTask.spec.ts, tests/resolvers/Mutation/updateUserProfile.spec.ts, tests/resolvers/Mutation/updateUserType.spec.ts
Refactoring
**Issue Number:** 
Fixes #1003 
Not Applicable 
Not Relevant 
**Summary**
- This PR refactors file 61 to 70
- Removing the conditional check `process.env !== "PRODUCTION"` for `requestContext.translate()`
- Also added new constants where needed
No
All tests cases are passing as shown below -
Yes
=> Mutations: Refactored file 61 to 70, removing conditional check for PRODUCTION

src/resolvers/Query/getDonationByOrgIdConnection.ts, src/typeDefs/queries.ts, src/types/generatedGraphQLTypes.ts
Adds non-nullable type in list and adds first and skip in connection.
Fixes #1052 
No, to avoid heavier PR.
No
Yes
=> Adds non-nullable type in list and adds first and skip in connection.

tests/libraries/logger.spec.ts
Bugfix 
Fixes #1109 
Yes
Now the tests pass irrespective of `COLOURIZE_LOGS` property in the `.env`
NA
**Summary**
Corrected the method for testing colourization in the logger.
No
NA
Yes
=> Update tests for logger.ts [Fixes #1109]

src/constants.ts, src/libraries/requestUrl.ts, src/resolvers/Organization/image.ts, src/server.ts, tests/resolvers/Organization/image.spec.ts
This PR adds the dynamic apiRootUrl into context of all requests which returns a url based on the current server's hostname and protocol.
Fixes #1131 
Yes
Not Relevant
Not Required
**Summary**
This PR adds the dynamic apiRootUrl into context of all requests which returns a url based on the current server's hostname and protocol.
No
This makes the current Talawa-API images logic to work in remote production or development servers.
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md …
=> Add dynamic base url support for images to work in production environments [Fixes #1131]

src/server.ts
This PR adds the warning message based on creation of super user and if the variable is set in env file.
Fixes #1154 
I tested it manually.
No
**Summary**
Many users are facing setting up the repo locally because of creating the super admin, This change will help them provide info and a possible place to look where changes are need to make.
No
The grammar needs to be improved and report any possible scenario that comes to mind for adding warnings regarding the same. …
=> adds warning for super admin and env variable

src/resolvers/Query/users.ts, tests/resolvers/Query/users.spec.ts
Bugfix
Fixes #1186
Yes
NA
Not Relevant
**Summary**
The problem -
- The User and Users queries have organizationsBlockedBy set to an empty array
- This is done on purpose so that users are not able to see which organizations they've been blocked by
- This breaks the Block/Unblock functionality in Talawa Admin
Solution -
- Now, the user needs to be authenticated to call `USERS` query
- If the user role is `ADMIN` or `SUPERADMIN`, then we are populating the `organizationsBlockedBy` field
- Otherwise returning `[]`
- We are also checking if the user is querying on themselves, and returning `[]` in that case
**Does …
=> Populating organizationsBlockedBy when query called by Admin/Superadmin

package-lock.json, src/utilities/graphqlConnectionFactory.ts, tests/utilities/graphqlConnectionFactory.spec.ts
feature: add graphql connection object factory function to easily create connection objects
Fixes #
Yes
-
-
**Summary**
Creating graphql connection objects from scratch for each resolver which should return a connection object is redundant. This function lets us create a connection object with sensible default fields which can be changed according to different logic within the resolver.
-
-
Yes
=> feature: add graphql connection object factory function

src/resolvers/Mutation/login.ts, tests/resolvers/Mutation/login.spec.ts
Feature
Fixes #1146 
Yes
NA
NA
**Summary**
Upon login, now an additional check would be done to see if the user's email matches the environment variable `LAST_RESORT_SUPERADMIN_EMAIL`. If the same is true, the user's privileges are updated to `SUPERADMIN`, so that the user does not have to manually configure the same in the database. 
No
NA
Yes
=> Activate the `LAST_RESORT_SUPERADMIN_EMAIL` feature on login [Fixes #1146]

src/constants.ts, src/resolvers/Mutation/updateUserType.ts, tests/resolvers/Mutation/updateUserType.spec.ts
Bugfix
Fixes #1207
Yes
NA
NA
**Summary**
Prevent a superadmin from downgrading their own role to prevent them from being locked out of the system.
No
NA
Yes
=> Prevent `SUPERADMIN` from downgrading their own roles [Fixes #1207]

.github/workflows/pull-request.yml
Feature
Fixes #1241 
No
NA
NA
**Summary**
Uodated the Pull Request action to run Linter, Formatter and Typechecker in the same job with multiple steps. This would cause the `npm ci` command to run only once, instead of three times, thus reducing the Workflow run time.
No
NA
Yes
=> Update workflow to club Code Quality jobs into a singular job [Fixes #1241]

src/resolvers/Query/users.ts, tests/resolvers/Query/users.spec.ts
Bugfix
Fixes #1260 
Yes
Not Relevant
**Summary**
- The `Users` Query returned the `UserNotFound` Error when none of the filters matched
- Other queries like the `organizationsConnection` returned an empty array instead
- This created problems in the admin when filtering users in the Organization People page
- And the filters didn't match any user
- I've fixed this issue to return an empty array instead
No
This issue will help solving https://github.com/PalisadoesFoundation/talawa-admin/issues/730 …
=> Returning Empty Array Instead of Throwing Error

src/resolvers/Mutation/adminRemoveGroup.ts, src/typeDefs/mutations.ts, src/types/generatedGraphQLTypes.ts
**What kind of change does this PR introduce?** This PR fixes the return type of `adminRemoveGroup` Mutation Resolver to `InterfaceGroupChat`
**Issue Number: #1307**
Fixes #1307
**Did you add tests for your changes? - Yes** The changes were tested against already coded test suites
**If relevant, did you update the documentation?** No
**Does this PR introduce a breaking change?** - No
**Have you read the [contributing guide](https://github.com/PalisadoesFoundation/talawa-api/blob/master/CONTRIBUTING.md)?** - Yes
=> resolved adminRemoveGroup return type error

schema.graphql, src/typeDefs/scalars.ts, src/types/generatedGraphQLTypes.ts
It removes the unused scalar Upload from the tyoeDefs which was causing the server to break since the duplicate is already added by apollo at runtime. Thus the server was failing due to duplicate types.
Fixes #1341
The test failed because of failure of graphql-validation error.
That is duplicate instances of Upload scalar 
1. First, Dynamically added by Apollo Server v2
2. Second added by typeDefs. 
**Summary**
Yes
=> Removes the `Upload` Scalar explicit declaration  

codegen.ts, schema.graphql, src/constants.ts, src/models/CheckIn.ts, src/models/Feedback.ts, src/models/index.ts, src/resolvers/Event/attendees.ts, src/resolvers/Event/averageFeedbackScore.ts, src/resolvers/Event/feedback.ts, src/resolvers/Event/index.ts, src/resolvers/Feedback/event.ts, src/resolvers/Feedback/index.ts, src/resolvers/Mutation/addFeedback.ts, src/resolvers/Mutation/index.ts, src/resolvers/Query/hasSubmittedFeedback.ts, src/resolvers/index.ts, src/typeDefs/inputs.ts, src/typeDefs/mutations.ts, src/typeDefs/queries.ts, src/typeDefs/types.ts, src/types/generatedGraphQLTypes.ts, tests/helpers/feedback.ts, tests/resolvers/Event/averageFeedbackScore.test.ts, tests/resolvers/Event/feedback.test.ts, tests/resolvers/Feedback/event.spec.ts, tests/resolvers/Mutation/addFeedback.spec.ts, tests/resolvers/Query/hasSubmittedFeedback.spec.ts
This PR introduces the necessary models as well the resolvers need to implement a Feedback system in Talawa API. 
NA
Yes
NA
NA
**Summary**
NA
No
NA
Yes
=> Introduce Feedback System

src/resolvers/Mutation/updateUserProfile.ts, tests/resolvers/Mutation/updateUserProfile.spec.ts
Bugfix
Fixes #1382 
Yes
**Summary**
Added a condition that will check if the user changed the email or not. If the email is changed then only it will check if the email already exists or not. Also changed "find" to "findOne" as we know only one user will have a email and it is faster. Unit test is also added.
Yes
=> UserUpdate email already exists error fix

src/models/Feedback.ts, src/resolvers/Event/averageFeedbackScore.ts, tests/helpers/feedback.ts, tests/resolvers/Event/averageFeedbackScore.test.ts, tests/resolvers/Mutation/addFeedback.spec.ts
Bugfix
Fixes #1405
Yes
NA
NA
**Summary**
As discussed with @palisadoes, the maximum feedback rating in event management should be `5` to maintain consistency. This PR updates the same to be 5 instead of 10. 
No
NA
Yes
=> Make maximum rating of events in feedback to 5 [Fixes #1405]

src/resolvers/Mutation/removeOrganization.ts, src/resolvers/Mutation/removePost.ts, tests/resolvers/Mutation/removeOrganization.spec.ts, tests/resolvers/Mutation/removePost.spec.ts
Bugfix
Fixes #1424 
Yes
**Summary**
This PR makes sure that when Posts and Organization is deleted, there image is also deleted from file system and encodedImages.
Yes
**After changes**
https://github.com/PalisadoesFoundation/talawa-api/assets/123248648/dd5b6ca7-471e-46e5-8391-83ed80b74f14
=> Post and Organization image deletion fixed

Dockerfile, INSTALLATION.md, docker-compose.yaml, setup.ts
Added Dockerfile and docker-compose file for easy setup locally
Fixes PalisadoesFoundation/talawa-admin#974
No
N/A
Yes Updated the Docs
No
**Summary:**
I have created method to quickly setup talawa-api on local machines using Docker. The Dockerfile will create a docker image of the talawa-api. Then docker-compose will pull mongodb and redis images from docker hub and will start them locally as containers with talawa-api container.
This PR is Releated to this issue  - https://github.com/PalisadoesFoundation/talawa-admin/issues/974
**Have you read …
=> Issue#974 in talawa-api (Docker for Easy Local Devlopment)

.github/dependabot.yaml
[grouping] is not available for npm package management
bugfix
Fixes #1453
NA
NA
NA
**Summary**
This PR introduces a bugfix to address the ignored configuration issue identified in the recent dependabot run.
No
None
Yes
=> Feat: Fix issue #1453

package-lock.json, package.json
Reverts PalisadoesFoundation/talawa-api#1473
1. I'm going to have to revert this. It's causing our push.yml workflow to fail. 
1. Please check it out:
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7152285097
=> Revert "Feat: Upgrade package express-rate-limit from 5.5.1 to 7.1.5 #1463"

package-lock.json, package.json
Reverts PalisadoesFoundation/talawa-api#1501
I'm going to have to revert this. It's causing errors in our documentation workflow.
Please take a look at the error message we are getting to determine the cause of the problem
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7232029454
=> Revert "dotenv 16.3.1 upgrade"

.github/workflows/inspect.yml, .github/workflows/pull-request.yml
Added caching of node_modules for GitHub workflows. Caching was only needed in these 2 files coz other workflows are using `actions/setup-node@v3` action, which comes with caching.
Fixes #1471
This changes doesn't require tests.
NO
YES
=> Added node_modules caching for CI workflows.

setup.ts
- This is PR is a **feature** as requested in #1550 
- Fixes #1550
No
- When `LAST_RESORT_SUPERADMIN_EMAIL` is not configured:
[not_configured.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/116624667/fb48063e-3479-4610-8af9-dc2fadadbaa6)
- When `LAST_RESORT_SUPERADMIN_EMAIL` is configured:
[configured.webm](https://github.com/PalisadoesFoundation/talawa-api/assets/116624667/7085df2e-207d-4ec2-845f-5b6c8d2b8156)
There's no need to change the documentation.
**Summary**
- **Motivation** : When running the `npm run setup` command, if the `LAST_RESORT_SUPERADMIN_EMAIL` value has not been configured, …
=> feat: Updated the LAST_RESORT_SUPERADMIN_EMAIL logic during setup

src/app.ts
Bug Fix: Images doesn't render on the frontend because same-origin policy in server blocks access to image stored inside the images folder on the server.
Fixes #1626 
Before:
After:
Posts along with the image now renders.
=> Fixes access to image from the frontend

package-lock.json, package.json
- this is to fix `import:sample-data` script
Fixes #1679 
N/A
N/A
N/A
**Summary**
It downgrade the nanoId version, to resolve the CommonJS support issue in nanoid 4 or higher, which fixes the error when running script `import:sample-data`
No
Yes
=> fix: downgraded to nanoid@3.3.7

scripts/cloud-api-demo/deploy.sh
Bugfix mentioned here - https://github.com/PalisadoesFoundation/talawa-api/issues/1428#issuecomment-1891002800
None
N/A
N/A
N/A
**Summary**
The cloud instance of talawa-api was out of storage due to old containers and images created by workflow: 
Added the step to remove all the unwanted images and containers after the talawa-api containers are up and running in deploy.yaml workflow.
No
N/A
Yes
=> fix: removes all unused containers and images after deploy.yaml workflow

.github/workflows/inspect.yml, .github/workflows/push.yml
Reverts PalisadoesFoundation/talawa-api#1718
This has to be reverted. It's failing:
- https://github.com/PalisadoesFoundation/talawa-api/actions/runs/7603568839/job/20705612488
=> Revert "Merge : inpect.yml into push.yml"

src/constants.ts, src/resolvers/Mutation/createPost.ts, src/resolvers/Mutation/togglePostPin.ts, src/resolvers/Mutation/updatePost.ts, src/typeDefs/mutations.ts, src/types/generatedGraphQLTypes.ts, tests/resolvers/Mutation/createPost.spec.ts, tests/resolvers/Mutation/togglePostPin.spec.ts, tests/resolvers/Mutation/updatePost.spec.ts
**Issue Number: #1739**
Fixes #1739
Deprecated title for non-pinned posts
Following API endpoints are changed:
- Create post
- Update post
- Toggle post pin
Title should be provided to pin post. Non pinned posts will throw error if title is provided.
In toggle post pin, an input for title should be provided on the client side if the post is getting pinned, and the title will be automatically removed if the post is getting unpinned.
Yes
No
Yes
Yes
=> Deprecated titles for non-pinned posts

.husky/pre-commit, README.md, package-lock.json, package.json
This PR adds a pre-commit script run, to fix formatting
Fixes #1778 
**Summary**
=> feat: fix formatting before commit

.github/workflows/pull-request.yml
bugfix
Fixes #1548
**Summary**
=> fix: use HEAD^1 to refer to the parent commit instead of using 2 commits

.github/workflows/pull-request.yml, src/app.ts, src/checks.ts
=> feat: linting using changed-files gh action

tests/resolvers/Mutation/createPost.spec.ts
Tests added for increasing the code coverage of the file src/resolvers/Mutation/createPost.ts.
Fixes #1826 
N/A
All tests:
Code coverage of file src/resolvers/Mutation/createPost.ts after adding tests
N/A
No
Yes
=> Added tests for file src/resolvers/Mutation/createPost.ts

src/utilities/graphQLConnection/generateDefaultGraphQLConnection.ts, src/utilities/graphQLConnection/getCommonGraphQLConnectionFilter.ts, src/utilities/graphQLConnection/getCommonGraphQLConnectionSort.ts, src/utilities/graphQLConnection/index.ts, src/utilities/graphQLConnection/parseGraphQLConnectionArguments.ts, src/utilities/graphQLConnection/parseGraphQLConnectionArgumentsWithSortedBy.ts, src/utilities/graphQLConnection/parseGraphQLConnectionArgumentsWithSortedByAndWhere.ts, src/utilities/graphQLConnection/parseGraphQLConnectionArgumentsWithWhere.ts, src/utilities/graphQLConnection/transformToDefaultGraphQLConnection.ts, tests/resolvers/UserTag/childTags.spec.ts, tests/resolvers/UserTag/usersAssignedTo.spec.ts, tests/utilities/graphqlConnection.spec.ts
refactoring
Issue #1887
No
-
-
**Summary**
Updated tsdoc comments for connection utilities to show basic examples for implementation.
No
-
Yes
=> removed usage of any keyword from connection utilities, improved tsdoc comments

schema.graphql, src/helpers/event/deleteEventHelpers/deleteRecurringEvent.ts, src/helpers/event/deleteEventHelpers/deleteRecurringEventInstances.ts, src/helpers/event/deleteEventHelpers/deleteSingleEvent.ts, src/helpers/event/deleteEventHelpers/index.ts, src/helpers/event/updateEventHelpers/index.ts, src/helpers/event/updateEventHelpers/shouldUpdateBaseRecurringEvent.ts, src/helpers/event/updateEventHelpers/updateAllInstances.ts, src/helpers/event/updateEventHelpers/updateThisAndFollowingInstances.ts, src/resolvers/Mutation/removeEvent.ts, src/typeDefs/enums.ts, src/typeDefs/mutations.ts, src/types/generatedGraphQLTypes.ts, tests/helpers/events.ts, tests/resolvers/Mutation/removeEvent.spec.ts
It implements the functionality for deleting recurring events: this instance, this and following instances, and all instances.
Fixes #1583 
Yes
1. **Deleting this instance only**:
https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/6b9abf95-8481-4a57-8be6-d02cee998a4e
2. **Deleting this and the following instances**:
https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/a4e2404d-d5a7-45a6-96d7-8e84a92abdd7
3. **Deleting all the instances (except the exception instance)**:
https://github.com/PalisadoesFoundation/talawa-api/assets/55585268/f611805a-d87c-494a-b79c-975da20a66b5
> **For creation and management of recurring events, we're following [this](https://meetulr.github.io/Recurrence-Plan/) approach. Please refer to the corresponding section in there for a …
=> feat: delete recurring events

.eslintrc.json
refactor
Fixes #1944
Not required
-
-
**Summary**
Explained in the issue #1944
`"@typescript-eslint/no-inferrable-types"` rule is deleted, because explicit typing increases the performance of typescript language server and reduces the time it takes to type check the codebase.
-
-
Yes
=> changed eslint typescript no explicit any rule to warn

sample_data/appUserProfiles.json, src/resolvers/Query/users.ts, tests/resolvers/Query/users.spec.ts
A bugfix.
Fixes #2047 
No.
It's loading now.
**Summary**
In the follwoing PR, I corrected some appUserProfiles which had incorrect userId and made the users resolver return a default value for appUserProfile when appUserProfile was `null`.
No.
Yes.
=> Fixed continuous loading in 'Users' tab

codegen.ts, schema.graphql, src/constants.ts, src/helpers/event/recurringEventHelpers/createRecurrenceRule.ts, src/helpers/event/recurringEventHelpers/generateRecurrenceRuleString.ts, src/models/RecurrenceRule.ts, src/resolvers/Event/index.ts, src/resolvers/Event/recurrenceRule.ts, src/typeDefs/enums.ts, src/typeDefs/inputs.ts, src/typeDefs/types.ts, src/types/generatedGraphQLTypes.ts, src/utilities/recurrenceDatesUtil.ts, tests/resolvers/Event/recurrenceRule.spec.ts, tests/resolvers/Mutation/createEvent.spec.ts
1) Adds `recurrenceRule` field and the corresponding field resolver to the `Event` schema, which is to be used while updating recurring events PalisadoesFoundation/talawa-admin#1643.
2) Adds more recurrence properties to the `RecurrenceRule`, i.e. `interval`, `bysetpos` [link](https://github.com/jkbrzt/rrule#api).
Fixes #2090 
Yes
=> feat: Add `recurrenceRule` field resolver, and more recurrence properties

src/resolvers/Subscription/onPluginUpdate.ts, tests/resolvers/Subscription/onPluginUpdate.spec.ts
refactor, tests
Fixes #1923
Yes
No
Yes
=> refactor onPluginUpdate, added tests for it

tests/resolvers/Mutation/removeUserFamily.spec.ts
Tests for `removeUserFamily.ts` file.
Fixes #2066 
Yes
N/A
**Summary**
- Ensured 100% code coverage for `removeUserFamily.ts` file.
No
Yes
=> test: Added tests for `removeUserFamily.ts`

src/helpers/event/deleteEventHelpers/deleteRecurringEventInstances.ts, src/helpers/event/deleteEventHelpers/deleteSingleEvent.ts, src/resolvers/Mutation/removeEvent.ts, tests/resolvers/Mutation/removeEvent.spec.ts
Adds comprehensive tests and corrects the code for `removeEvent` mutation.
Fixes #2053 #2054
Yes
=> fix: add tests for deleting recurring events

package.json, schema.graphql, src/resolvers/Query/getVenueByOrgId.ts, src/resolvers/Query/helperFunctions/getSort.ts, src/resolvers/Query/helperFunctions/getWhere.ts, src/resolvers/Query/index.ts, src/typeDefs/enums.ts, src/typeDefs/inputs.ts, src/typeDefs/queries.ts, src/types/generatedGraphQLTypes.ts, tests/helpers/venue.ts, tests/resolvers/Query/getVenueByOrgId.spec.ts
feature 
Fixes #2169 
Yes 
https://github.com/PalisadoesFoundation/talawa-api/assets/109027247/ac33a0e8-9e0d-4183-8001-c68e1264a007
**Summary**
- Added `getVenueByOrgId` query resolver with support for
- fetch venues specific to orgId
- sorting by capacity (ASC/DESC)
- Filtering by Description
- Filtering by Name
No
Yes
=> Added getVenueByOrgId Resolver with sorting/filtering

src/utilities/createSampleOrganizationUtil.ts, tests/resolvers/Mutation/createUserTag.spec.ts
Test fix
Fixes #2078 & fixes #2200
Yes
**Summary**
- Add tests for `createSampleOrganizationUtil`
- Add tests for `createUsertag`
- remove all `any` and eslint-disable and added type for errors
No
Yes
=> Test fix: `src/utilities/createSampleOrganizationUtil.ts` and `createUserTag`

src/resolvers/Mutation/signUp.ts, tests/resolvers/Mutation/signUp.spec.ts
Modifies sign-up mutation to populate user schema fields.
Fixes #2203 
Yes
=> fix: signup mutation data population error

src/resolvers/Mutation/updateEvent.ts, tests/resolvers/Mutation/updateEvent.spec.ts
A bugfix.
Fixes #2216  
Yes.
**Summary**
In the following PR, I have ensured that admins are able to update events.
No.
Yes.
=> Fix: Event details cannot be updated by Admins

src/resolvers/Mutation/unblockUser.ts, tests/resolvers/Mutation/unblockUser.spec.ts
This PR is a Bugfix
Fixes #2238
No.
[Screencast from 2024-04-21 15-55-44(1).webm](https://github.com/PalisadoesFoundation/talawa-api/assets/116624667/ec7b0edf-f565-4738-9236-f591f4fba9d6)
Not relevant.
**Summary**
The `UnblockUser` mutation was throwing `Unauthorized` error because it was using `context.userId` instead of `args.userId`. Now I have updated mutation to use `args.userId`, it's working without errors.
No.
=> fix: Fixed error in UnblockUser mutation

src/config/plugins/loadPlugins.ts, src/db.ts
bugfix
Fixes #2161
No
No
**Summary**
1. This PR resolves a bug causing server errors due to an incorrect MongoDB URI in the loadPlugin function.
2. It prevents multiple database connections during startup by implementing logic to check for existing connections before establishing a new one.
No
Yes
=> fix minor bug: ensure single database connection on server startup

.devcontainer/devcontainer.json, docker/api.Containerfile, package.json
Reverts PalisadoesFoundation/talawa-api#3152
=> Revert "Revert "Revert "pnpm roll back"""
